In [1]:
import pandas as pd
import pandas as pd
from pathlib import Path

In [2]:
data_dir = Path("/projects/immunestatus/rheum/airr_format")

metadata = pd.read_csv(data_dir / "metadata.tsv", sep='\t')

In [3]:
shep_init = pd.read_csv(data_dir / 'as_Shep_PB_F.tsv', sep='\t')

In [4]:
shep_init

        count       junction_aa    v_call   j_call locus
0       14805    CATSPGSSYNEQFF   TRBV7-2  TRBJ2-1  beta
1       13797    CSATRTARNQPQHF  TRBV20-1  TRBJ1-5  beta
2       12029    CASSPGLAIHEQFF   TRBV6-2  TRBJ2-1  beta
3       11766  CASTAPSGTGTDTQYF    TRBV27  TRBJ2-3  beta
4       11666     CASSSQGNTEAFF   TRBV7-3  TRBJ1-1  beta
...       ...               ...       ...      ...   ...
312049      1           WAHGYTF    TRBV27  TRBJ1-2  beta
312050      1            SHEQYF   TRBV5-5  TRBJ2-7  beta
312051      1            CAEAFF    TRBV30  TRBJ1-1  beta
312052      1            CASQFF    TRBV27  TRBJ2-1  beta
312053      1            CASYTF   TRBV5-1  TRBJ1-2  beta

[312054 rows x 5 columns]

In [21]:
clustering = pd.read_csv(
    '/projects/immunestatus/rheum/tcrempnet_b27pos_k8/as_Shep_PB_F_tcremp_clusters.tsv', sep='\t')

In [22]:
import sys
sys.path.append('/home/evlasova/mirpy')
from mir.common.clonotype_dataset import ClonotypeDataset
from mir.common.clonotype import ClonotypeAA

In [23]:
as_seqs = [
    'CASSVGLFSTDTQYF',
    'CASSVGLYSTDTQYF',
    'CASSAGLFSTDTQYF',
    'CASSAGLYSTDTQYF',
    'CASSLGLFSTDTQYF',
    'CASSLGLYSTDTQYF',
    'CASSPGLFSTDTQYF',
    'CASSPGLYSTDTQYF'
]
as_clonotypes = [ClonotypeAA(cdr3aa=x) for x in as_seqs]

In [24]:
as_clonotypes = [ClonotypeAA(cdr3aa=x) for x in as_seqs]
vdjdb = ClonotypeDataset(as_clonotypes)

In [25]:
def has_vdjdb_match(x, threshold=0):
    return len(vdjdb.get_matching_clonotypes(x, threshold=threshold)) > 0

In [26]:
shep_init['pattern'] = shep_init['junction_aa'].apply(has_vdjdb_match)

In [27]:
shep_init

        count       junction_aa    v_call   j_call locus  pattern
0       14805    CATSPGSSYNEQFF   TRBV7-2  TRBJ2-1  beta    False
1       13797    CSATRTARNQPQHF  TRBV20-1  TRBJ1-5  beta    False
2       12029    CASSPGLAIHEQFF   TRBV6-2  TRBJ2-1  beta    False
3       11766  CASTAPSGTGTDTQYF    TRBV27  TRBJ2-3  beta    False
4       11666     CASSSQGNTEAFF   TRBV7-3  TRBJ1-1  beta    False
...       ...               ...       ...      ...   ...      ...
312049      1           WAHGYTF    TRBV27  TRBJ1-2  beta    False
312050      1            SHEQYF   TRBV5-5  TRBJ2-7  beta    False
312051      1            CAEAFF    TRBV30  TRBJ1-1  beta    False
312052      1            CASQFF    TRBV27  TRBJ2-1  beta    False
312053      1            CASYTF   TRBV5-1  TRBJ1-2  beta    False

[312054 rows x 6 columns]

In [28]:
shep_init[shep_init['pattern']]

        count      junction_aa  v_call   j_call locus  pattern
778        31  CASSPGLFSTDTQYF   TRBV9  TRBJ2-3  beta     True
1759       16  CASSVGLYSTDTQYF   TRBV9  TRBJ2-3  beta     True
1913       15  CASSVGLFSTDTQYF   TRBV9  TRBJ2-3  beta     True
3712        9  CASSLGLYSTDTQYF   TRBV9  TRBJ2-3  beta     True
4337        8  CASSVGLFSTDTQYF   TRBV9  TRBJ2-3  beta     True
5153        7  CASSVGLFSTDTQYF   TRBV9  TRBJ2-3  beta     True
6340        6  CASSVGLYSTDTQYF   TRBV9  TRBJ2-3  beta     True
8166        5  CASSLGLFSTDTQYF   TRBV9  TRBJ2-3  beta     True
144452      1  CASSPGLFSTDTQYF  TRBV18  TRBJ2-3  beta     True
167078      1  CASSLGLYSTDTQYF   TRBV9  TRBJ2-3  beta     True
174352      1  CASSVGLFSTDTQYF   TRBV9  TRBJ2-3  beta     True

In [29]:
clustering['pattern'] = clustering.cdr3aa_beta.apply(has_vdjdb_match)

In [30]:
clustering[clustering.pattern]

        clone_id  cluster_id      cdr3aa_beta     v_beta      j_beta  pattern
778        s_778          -1  CASSPGLFSTDTQYF   TRBV9*01  TRBJ2-3*01     True
1759      s_1759         247  CASSVGLYSTDTQYF   TRBV9*01  TRBJ2-3*01     True
1913      s_1913         247  CASSVGLFSTDTQYF   TRBV9*01  TRBJ2-3*01     True
3712      s_3712         247  CASSLGLYSTDTQYF   TRBV9*01  TRBJ2-3*01     True
4337      s_4337         247  CASSVGLFSTDTQYF   TRBV9*01  TRBJ2-3*01     True
5153      s_5153         247  CASSVGLFSTDTQYF   TRBV9*01  TRBJ2-3*01     True
6340      s_6340         247  CASSVGLYSTDTQYF   TRBV9*01  TRBJ2-3*01     True
8166      s_8166         247  CASSLGLFSTDTQYF   TRBV9*01  TRBJ2-3*01     True
144449  s_144452          -1  CASSPGLFSTDTQYF  TRBV18*01  TRBJ2-3*01     True
167075  s_167078         247  CASSLGLYSTDTQYF   TRBV9*01  TRBJ2-3*01     True
174349  s_174352         247  CASSVGLFSTDTQYF   TRBV9*01  TRBJ2-3*01     True

In [31]:
clustering[clustering.cluster_id == 247]

        clone_id  cluster_id      cdr3aa_beta    v_beta      j_beta  pattern
1759      s_1759         247  CASSVGLYSTDTQYF  TRBV9*01  TRBJ2-3*01     True
1913      s_1913         247  CASSVGLFSTDTQYF  TRBV9*01  TRBJ2-3*01     True
3712      s_3712         247  CASSLGLYSTDTQYF  TRBV9*01  TRBJ2-3*01     True
4337      s_4337         247  CASSVGLFSTDTQYF  TRBV9*01  TRBJ2-3*01     True
5153      s_5153         247  CASSVGLFSTDTQYF  TRBV9*01  TRBJ2-3*01     True
6340      s_6340         247  CASSVGLYSTDTQYF  TRBV9*01  TRBJ2-3*01     True
8166      s_8166         247  CASSLGLFSTDTQYF  TRBV9*01  TRBJ2-3*01     True
167075  s_167078         247  CASSLGLYSTDTQYF  TRBV9*01  TRBJ2-3*01     True
174349  s_174352         247  CASSVGLFSTDTQYF  TRBV9*01  TRBJ2-3*01     True