In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/projects/immunestatus/vdjdb/pools/human.trb.aa.txt', sep='\t')

KeyboardInterrupt

In [ ]:
df

In [9]:
number_of_reads_overall = df['count'].sum()

In [16]:
df = df.sample(n=10**6)

In [26]:
import numpy as np
import pandas as pd

# df: большие данные с колонкой 'count' и любыми другими (cdr3nt, cdr3aa, ...)
counts = df['count'].to_numpy(dtype=np.int64)
target = 5_000_000
total = counts.sum()
p = target / total

# Биномиальное прореживание
keep = np.random.binomial(counts, p)

# Оставляем только строки с ненулевым отбором и «разворачиваем»
mask = keep > 0
sampled = df.loc[mask].copy()
sampled_counts = keep[mask]

# Если нужны именно риды как строки (а не агрегированные счётчики):
# индексы исходных строк, повторённые по числу отобранных ридов
idx_rep = np.repeat(sampled.index.to_numpy(), sampled_counts)
sampled_reads = df.loc[idx_rep]            # это 1e6 строк (примерно)

In [28]:
sampled = sampled_reads[['cdr3aa', 'v', 'j']].drop_duplicates()
sampled

                   cdr3aa         v        j
0         CATSDPGTGHQPQHF  TRBV24-1  TRBJ1-5
1         CAISEGLGQGETQYF  TRBV10-3  TRBJ2-5
2         CASSQVGTGVYEQYF   TRBV3-1  TRBJ2-7
3            CASSLGADTQYF    TRBV13  TRBJ2-3
4            CASSRTGNEQYF    TRBV27  TRBJ2-7
...                   ...       ...      ...
17955889  CASRIPTGTNTEAFF   TRBV5-1  TRBJ1-1
17955894      CSGAGTDTQYF  TRBV20-1  TRBJ2-3
17955902  CASSSQGRELTEAFF  TRBV12-4  TRBJ1-1
17955906  CASTRAGQLNTEAFF    TRBV28  TRBJ1-1
17955911  CASSQSIRDNYEQYF   TRBV4-1  TRBJ2-7

[2158513 rows x 3 columns]

In [29]:
sampled['locus'] = 'beta'

In [31]:
sampled = sampled.rename(columns={'cdr3aa': 'junction_aa', 
                        'v': 'v_call',
                        'j': 'j_call'})
sampled

              junction_aa    v_call   j_call locus
0         CATSDPGTGHQPQHF  TRBV24-1  TRBJ1-5  beta
1         CAISEGLGQGETQYF  TRBV10-3  TRBJ2-5  beta
2         CASSQVGTGVYEQYF   TRBV3-1  TRBJ2-7  beta
3            CASSLGADTQYF    TRBV13  TRBJ2-3  beta
4            CASSRTGNEQYF    TRBV27  TRBJ2-7  beta
...                   ...       ...      ...   ...
17955889  CASRIPTGTNTEAFF   TRBV5-1  TRBJ1-1  beta
17955894      CSGAGTDTQYF  TRBV20-1  TRBJ2-3  beta
17955902  CASSSQGRELTEAFF  TRBV12-4  TRBJ1-1  beta
17955906  CASTRAGQLNTEAFF    TRBV28  TRBJ1-1  beta
17955911  CASSQSIRDNYEQYF   TRBV4-1  TRBJ2-7  beta

[2158513 rows x 4 columns]

In [35]:
sampled.to_csv('/projects/immunestatus/vdjdb/airr_format/trb_background.tsv', sep='\t', index=False)

In [3]:
df = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/vdjdb_full_filtered.txt', sep='\t')

/scratch/ipykernel_37388/3455155727.py:1: DtypeWarning: Columns (5,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/vdjdb_full_filtered.txt', sep='\t')

In [4]:
df = df[df.species == 'HomoSapiens']

In [5]:
df[df['cdr3.beta'].notna()][['cdr3.beta', 'v.beta', 'j.beta', 'antigen.epitope']]

               cdr3.beta     v.beta      j.beta       antigen.epitope
0          CASSIVGGNEQFF  TRBV19*01  TRBJ2-1*01             GILGFVFTL
1          CASSMRSTGELFF  TRBV19*01  TRBJ2-2*01             GILGFVFTL
2          CASSIRSAWAQYF  TRBV19*01  TRBJ2-3*01             GILGFVFTL
3          CASSQRSTGELFF  TRBV19*01  TRBJ2-2*01             GILGFVFTL
4          CASSIRSSYEQYF  TRBV19*01  TRBJ2-7*01             GILGFVFTL
...                  ...        ...         ...                   ...
107954   CASSPSARGNQPQHF   TRBV2*01  TRBJ1-5*01  FRDYVDRFYKTLRAEQASQE
107955   CASSVGTSGVGEQYF   TRBV2*01  TRBJ2-7*01  FRDYVDRFYKTLRAEQASQE
107956   CASSALASGGDTQYF   TRBV2*01  TRBJ2-3*01  FRDYVDRFYKTLRAEQASQE
107957   CASSRLAGGMDEQFF   TRBV2*01  TRBJ2-1*01  FRDYVDRFYKTLRAEQASQE
107958  CASSRRTSGGTDTQYF   TRBV2*01  TRBJ2-3*01  FRDYVDRFYKTLRAEQASQE

[93838 rows x 4 columns]

In [6]:
common_epitopes = df[df['cdr3.beta'].notna()][
    ['cdr3.beta', 'v.beta', 'j.beta', 'antigen.epitope']]['antigen.epitope'].value_counts().head(10).index

In [7]:
df = df[df['cdr3.beta'].notna()][
    ['cdr3.beta', 'v.beta', 'j.beta', 'antigen.epitope']].dropna().drop_duplicates().reset_index(names='clone_id')
df['locus'] = 'beta'

In [8]:
df = df.rename(columns={'cdr3.beta': 'junction_aa', 'v.beta': 'v_call', 'j.beta': 'j_call' })

In [9]:
df

,clone_id,junction_aa,v_call,j_call,antigen.epitope,locus
0,0,CASSIVGGNEQFF,TRBV19*01,TRBJ2-1*01,GILGFVFTL,beta
1,1,CASSMRSTGELFF,TRBV19*01,TRBJ2-2*01,GILGFVFTL,beta
2,2,CASSIRSAWAQYF,TRBV19*01,TRBJ2-3*01,GILGFVFTL,beta
3,3,CASSQRSTGELFF,TRBV19*01,TRBJ2-2*01,GILGFVFTL,beta
4,4,CASSIRSSYEQYF,TRBV19*01,TRBJ2-7*01,GILGFVFTL,beta
...,...,...,...,...,...,...
77873,107939,CASSRWASGGDEQFF,TRBV2*01,TRBJ2-1*01,FRDYVDRFYKTLRAEQASQE,beta
77874,107941,CASSARTSGGGDTQYF,TRBV2*01,TRBJ2-3*01,FRDYVDRFYKTLRAEQASQE,beta
77875,107942,CASSARTSGGQDEQFF,TRBV2*01,TRBJ2-1*01,FRDYVDRFYKTLRAEQASQE,beta
77876,107943,CASSARTSGGRDTQYF,TRBV2*01,TRBJ2-3*01,FRDYVDRFYKTLRAEQASQE,beta
77877,107951,CASSAMASGSDTQYF,TRBV2*01,TRBJ2-3*01,FRDYVDRFYKTLRAEQASQE,beta

In [10]:
for epi in common_epitopes:
    vdjdb_epi = df[df['antigen.epitope'] == epi].drop(columns=['antigen.epitope']).drop_duplicates()
    vdjdb_epi.to_csv(
        f'/projects/immunestatus/vdjdb/airr_format/trb_vdjdb_uni_{epi}.tsv', sep='\t', index=False)

In [11]:
df.to_csv(
    '/projects/immunestatus/vdjdb/airr_format/trb_vdjdb_uni.tsv', sep='\t', index=False)