In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/vdjdb_full_filtered.txt', sep='\t')

/scratch/ipykernel_1470668/3455155727.py:1: DtypeWarning: Columns (5,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/vdjdb_full_filtered.txt', sep='\t')

In [3]:
df.columns

Index(['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'd.beta',
       'j.beta', 'species', 'mhc.a', 'mhc.b', 'mhc.class', 'antigen.epitope',
       'antigen.gene', 'antigen.species', 'reference.id',
       'method.identification', 'method.frequency', 'method.singlecell',
       'method.sequencing', 'method.verification', 'meta.study.id',
       'meta.cell.subset', 'meta.subject.cohort', 'meta.subject.id',
       'meta.replica.id', 'meta.clone.id', 'meta.epitope.id', 'meta.tissue',
       'meta.donor.MHC', 'meta.donor.MHC.method', 'meta.structure.id',
       'cdr3fix.alpha', 'cdr3fix.beta', 'vdjdb.score'],
      dtype='object')

In [4]:
df['antigen.epitope'].value_counts()

antigen.epitope
SLLMWITQV    29699
KLGGALQAK    13726
GILGFVFTL    13539
NLVPMVATV     7158
GLCTLVAML     3339
             ...
KMGVTYEM         1
FMGVTYEM         1
LMDMHNGQL        1
RLDAMNGQL        1
RMDYNNMQM        1
Name: count, Length: 1711, dtype: int64

In [5]:
col_mapping = {x: x.replace('.', '_') for x in df.columns}
df = df.rename(columns=col_mapping)

In [6]:
df[df['antigen_epitope'] == 'GILGFVFTL']['reference_id'].value_counts()

reference_id
PMID:28423320                                                                                                                                                                  3985
PMID:37749325                                                                                                                                                                  3409
PMID:40694338                                                                                                                                                                  1887
https://www.10xgenomics.com/resources/application-notes/a-new-way-of-exploring-immunity-linking-highly-multiplexed-antigen-recognition-to-immune-repertoire-and-phenotype/#    1328
PMID:25609818                                                                                                                                                                   843
PMID:34811538                                                                                                                                                                   616
PMID:28636589                                                                                                                                                                   422
PMID:28636592                                                                                                                                                                   255
PMID:28250417                                                                                                                                                                   194
PMID:34793243                                                                                                                                                                   141
PMID:29997621                                                                                                                                                                   133
PMID:29483513                                                                                                                                                                   121
PMID:28629751                                                                                                                                                                    83
PMID:27645996                                                                                                                                                                    43
PMID:7807026                                                                                                                                                                     39
PMID:25339770                                                                                                                                                                    17
PMID:25801351                                                                                                                                                                    16
https://github.com/antigenomics/vdjdb-db/issues/215                                                                                                                               2
PMID:18275829                                                                                                                                                                     2
PMID:21562156                                                                                                                                                                     1
PMID:12796775                                                                                                                                                                     1
PMID:28931605                                                                                                                                                                     1
Name: count, dtype: int64

In [7]:
df.meta_study_id

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
107954    NaN
107955    NaN
107956    NaN
107957    NaN
107958    NaN
Name: meta_study_id, Length: 107959, dtype: object

In [8]:
df.columns

Index(['cdr3_alpha', 'v_alpha', 'j_alpha', 'cdr3_beta', 'v_beta', 'd_beta',
       'j_beta', 'species', 'mhc_a', 'mhc_b', 'mhc_class', 'antigen_epitope',
       'antigen_gene', 'antigen_species', 'reference_id',
       'method_identification', 'method_frequency', 'method_singlecell',
       'method_sequencing', 'method_verification', 'meta_study_id',
       'meta_cell_subset', 'meta_subject_cohort', 'meta_subject_id',
       'meta_replica_id', 'meta_clone_id', 'meta_epitope_id', 'meta_tissue',
       'meta_donor_MHC', 'meta_donor_MHC_method', 'meta_structure_id',
       'cdr3fix_alpha', 'cdr3fix_beta', 'vdjdb_score'],
      dtype='object')

In [11]:
df[df.cdr3_beta == 'CASSWGGGSHYGYTF']['antigen_epitope'].value_counts()

antigen_epitope
IVTDFSVIK     130
RAKFKQLL        9
GILGFVFTL       7
AVFDRKSDAK      2
KLGGALQAK       2
Name: count, dtype: int64

In [12]:
df[df.cdr3_beta == 'CASSWGGGSHYGYTF'].groupby(['reference_id', 'antigen_epitope']).nunique()

                                                                    cdr3_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                2
                                                   GILGFVFTL                 6
                                                   IVTDFSVIK               124
                                                   KLGGALQAK                 2
                                                   RAKFKQLL                  8

                                                                    v_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK             2
                                                   GILGFVFTL              5
                                                   IVTDFSVIK             39
                                                   KLGGALQAK              2
                                                   RAKFKQLL               6

                                                                    j_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK             2
                                                   GILGFVFTL              3
                                                   IVTDFSVIK             42
                                                   KLGGALQAK              2
                                                   RAKFKQLL               7

                                                                    cdr3_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK               1
                                                   GILGFVFTL                1
                                                   IVTDFSVIK                1
                                                   KLGGALQAK                1
                                                   RAKFKQLL                 1

                                                                    v_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK            1
                                                   GILGFVFTL             2
                                                   IVTDFSVIK             2
                                                   KLGGALQAK             1
                                                   RAKFKQLL              2

                                                                    d_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK            1
                                                   GILGFVFTL             1
                                                   IVTDFSVIK             1
                                                   KLGGALQAK             1
                                                   RAKFKQLL              1

                                                                    j_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK            1
                                                   GILGFVFTL             1
                                                   IVTDFSVIK             1
                                                   KLGGALQAK             1
                                                   RAKFKQLL              1

                                                                    species  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK             1
                                                   GILGFVFTL              1
                                                   IVTDFSVIK              1
                                                   KLGGALQAK              1
                                                   RAKFKQLL               1

                                                                    mhc_a  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK           1
                                                   GILGFVFTL            1
                                                   IVTDFSVIK            1
                                                   KLGGALQAK            1
                                                   RAKFKQLL             1

                                                                    mhc_b  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK           1
                                                   GILGFVFTL            1
                                                   IVTDFSVIK            1
                                                   KLGGALQAK            1
                                                   RAKFKQLL             1

                                                                    ...  \
reference_id                                       antigen_epitope  ...
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK       ...
                                                   GILGFVFTL        ...
                                                   IVTDFSVIK        ...
                                                   KLGGALQAK        ...
                                                   RAKFKQLL         ...

                                                                    meta_replica_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                     0
                                                   GILGFVFTL                      0
                                                   IVTDFSVIK                      0
                                                   KLGGALQAK                      0
                                                   RAKFKQLL                       0

                                                                    meta_clone_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                   0
                                                   GILGFVFTL                    0
                                                   IVTDFSVIK                    0
                                                   KLGGALQAK                    0
                                                   RAKFKQLL                     0

                                                                    meta_epitope_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                     0
                                                   GILGFVFTL                      0
                                                   IVTDFSVIK                      0
                                                   KLGGALQAK                      0
                                                   RAKFKQLL                       0

                                                                    meta_tissue  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                 0
                                                   GILGFVFTL                  0
                                                   IVTDFSVIK                  0
                                                   KLGGALQAK                  0
                                                   RAKFKQLL                   0

                                                                    meta_donor_MHC  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                    0
                                                   GILGFVFTL                     0
                                                   IVTDFSVIK                     0
                                                   KLGGALQAK                     0
                                                   RAKFKQLL                      0

                                                                    meta_donor_MHC_method  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                           0
                                                   GILGFVFTL                            0
                                                   IVTDFSVIK                            0
                                                   KLGGALQAK                            0
                                                   RAKFKQLL                             0

                                                                    meta_structure_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                       0
                                                   GILGFVFTL                        0
                                                   IVTDFSVIK                        0
                                                   KLGGALQAK                        0
                                                   RAKFKQLL                         0

                                                                    cdr3fix_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                   2
                                                   GILGFVFTL                    6
                                                   IVTDFSVIK                  124
                                                   KLGGALQAK                    2
                                                   RAKFKQLL                     8

                                                                    cdr3fix_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                  1
                                                   GILGFVFTL                   2
                                                   IVTDFSVIK                   2
                                                   KLGGALQAK                   1
                                                   RAKFKQLL                    2

                                                                    vdjdb_score
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                 1
                                                   GILGFVFTL                  1
                                                   IVTDFSVIK                  2
                                                   KLGGALQAK                  1
                                                   RAKFKQLL                   1

[5 rows x 32 columns]

In [13]:
import pandas as pd

def _normalize_chain(chain: str) -> str:
    """Accepts alpha/beta or TRA/TRB; returns 'alpha' or 'beta'."""
    chain = chain.strip().upper()
    if chain in {"ALPHA", "TRA", "TRAV", "TCRA"}:
        return "alpha"
    if chain in {"BETA", "TRB", "TRBV", "TCRB"}:
        return "beta"
    raise ValueError(f"Unknown chain: {chain!r}. Use alpha/beta or TRA/TRB.")


def get_epitope_specific_clonotypes(
    df: pd.DataFrame,
    epitope: str,
    chain: str = "beta",
):
    """
    Epitope-specific clonotypes:
      • clonotype is associated ONLY with the given epitope across the dataset
        (considering rows where antigen_epitope is not null)

    Returns a DataFrame with clonotype columns and:
      - epitope
      - n_studies (unique reference_id count within the epitope rows)
    """
    chain = _normalize_chain(chain)

    clonotype_cols = [f"cdr3_{chain}", f"v_{chain}", f"j_{chain}"]

    df_annot = df[df["antigen_epitope"].notna()].copy()
    df_annot = df_annot.dropna(subset=clonotype_cols)

    # epitope set per clonotype
    epi_sets = (
        df_annot
        .groupby(clonotype_cols)["antigen_epitope"]
        .agg(lambda x: set(x))
    )

    specific_idx = epi_sets[epi_sets == {epitope}].index

    df_target = df_annot[df_annot["antigen_epitope"] == epitope].copy()
    df_target = df_target.set_index(clonotype_cols).loc[specific_idx].reset_index()

    n_studies = (
        df_target
        .groupby(clonotype_cols)["reference_id"]
        .nunique()
        .rename("n_studies")
        .reset_index()
    )

    n_studies["epitope"] = epitope
    return n_studies


def get_public_epitope_specific_clonotypes(
    df: pd.DataFrame,
    epitope: str,
    chain: str = "beta",
    min_studies: int = 2,
):
    """
    Public + epitope-specific clonotypes:
      • epitope-specific (only this epitope across dataset)
      • present in >= min_studies studies (unique reference_id)

    Returns a DataFrame with clonotype columns and:
      - epitope
      - n_studies
    """
    specific = get_epitope_specific_clonotypes(df, epitope=epitope, chain=chain)
    public = specific[specific["n_studies"] >= int(min_studies)].copy()
    return public


def topN_specific_and_public(
    df: pd.DataFrame,
    chain: str = "beta",
    min_studies: int = 2,
    n_epi: int = 20,
):
    """
    For top-N epitopes (by #unique clonotypes) compute:
      - specific clonotypes
      - public+specific clonotypes (>= min_studies studies)

    Returns: (specific_df, public_df, top_epitopes_series)
    """
    chain_norm = _normalize_chain(chain)
    cols = [f"cdr3_{chain_norm}", f"v_{chain_norm}", f"j_{chain_norm}"]

    uniq = (
        df[df["antigen_epitope"].notna()]
        .dropna(subset=cols)
        .drop_duplicates(subset=["antigen_epitope"] + cols)
        .groupby("antigen_epitope")
        .size()
        .sort_values(ascending=False)
    )

    top_epitopes = uniq.head(n_epi).index.tolist()

    specific_parts = [get_epitope_specific_clonotypes(df, ep, chain_norm) for ep in top_epitopes]
    public_parts = [get_public_epitope_specific_clonotypes(df, ep, chain_norm, min_studies) for ep in top_epitopes]

    specific_df = pd.concat(specific_parts, ignore_index=True) if specific_parts else pd.DataFrame()
    public_df = pd.concat(public_parts, ignore_index=True) if public_parts else pd.DataFrame()

    # add chain label for downstream merges / saving
    specific_df["chain"] = chain_norm
    public_df["chain"] = chain_norm

    return specific_df, public_df, uniq.head(n_epi)

In [14]:
hits = get_public_epitope_specific_clonotypes(
    df,
    epitope="GILGFVFTL",
    chain="beta",
    min_studies=2
)

hits

             cdr3_beta       v_beta      j_beta  n_studies    epitope
3         CAASTGIYGYTF    TRBV19*01  TRBJ1-2*01          2  GILGFVFTL
10       CACSGTEDQPQHF    TRBV30*01  TRBJ1-5*01          2  GILGFVFTL
13        CACSQGSYGYTF    TRBV19*01  TRBJ1-2*01          2  GILGFVFTL
29     CAIKLRGSEGDTQYF    TRBV28*01  TRBJ2-3*01          2  GILGFVFTL
30       CAILGYGSTEAFF  TRBV12-3*01  TRBJ1-1*01          2  GILGFVFTL
...                ...          ...         ...        ...        ...
4978     CSVGEGGYTEAFF  TRBV29-1*01  TRBJ1-1*01          2  GILGFVFTL
4990        CSVITDTQYF  TRBV29-1*01  TRBJ2-3*01          2  GILGFVFTL
5013  CSVSTLLRGFNYGYTF  TRBV20-1*01  TRBJ1-2*01          2  GILGFVFTL
5015    CSVVASGNPDTQYF  TRBV29-1*01  TRBJ2-3*01          2  GILGFVFTL
5020     CSVVSRDSYEQYF  TRBV29-1*01  TRBJ2-7*01          2  GILGFVFTL

[1105 rows x 5 columns]

In [15]:
def top10_public_specific(df, chain="beta", min_studies=2, n_epi=20):

    cols = [f"cdr3_{chain}", f"v_{chain}", f"j_{chain}"]
    if chain == "beta" and f"d_{chain}" in df.columns:
        cols.append(f"d_{chain}")

    # --- считаем уникальные клонотипы на эпитоп ---
    uniq = (
        df[df["antigen_epitope"].notna()]
        .drop_duplicates(subset=["antigen_epitope"] + cols)
        .groupby("antigen_epitope")
        .size()
        .sort_values(ascending=False)
    )

    top_epitopes = uniq.head(n_epi).index

    # --- собираем результаты ---
    parts = [
        get_public_epitope_specific_clonotypes(df, ep, chain, min_studies)
        for ep in top_epitopes
    ]

    return pd.concat(parts, ignore_index=True), uniq.head(n_epi)

In [16]:
# beta: specific + public
specific_trb, public_trb, top10_trb = topN_specific_and_public(df, chain="TRB", min_studies=2, n_epi=20)

print("Top epitopes (TRB) by #unique clonotypes:")
display(top10_trb.rename("n_unique_clonotypes").to_frame())

print("Specific TRB clonotypes (preview):")
display(specific_trb.head())

print("Public+specific TRB clonotypes (preview):")
display(public_trb.head())

Top epitopes (TRB) by #unique clonotypes:

                 n_unique_clonotypes
antigen_epitope
SLLMWITQV                      29697
KLGGALQAK                      12530
GILGFVFTL                       5229
NLVPMVATV                       4646
AVFDRKSDAK                      1617
ELAGIGILTV                      1427
RAKFKQLL                        1355
GLCTLVAML                       1207
YLQPRTFLL                        930
LLAGIGTVPI                       831
IVTDFSVIK                        545
CTPYDINQM                        544
TTPESANL                         533
SPRWYFYYL                        518
KRWIILGLNK                       461
TFEYVSQPFLMDLE                   442
YVLDHLIVV                        420
TTDPSFLGRY                       418
LLWNGPMAV                        406
RLRAEAQVK                        405

Specific TRB clonotypes (preview):

            cdr3_beta      v_beta      j_beta  n_studies    epitope chain
0      CASSAADRSGELFF  TRBV6-5*01  TRBJ2-2*01          1  SLLMWITQV  beta
1  CASSAAFSTQSYGGELFF  TRBV6-5*01  TRBJ2-2*01          1  SLLMWITQV  beta
2      CASSAAGAAGELFF  TRBV6-5*01  TRBJ2-2*01          1  SLLMWITQV  beta
3  CASSAAGAAGVSGGELFF  TRBV6-5*01  TRBJ2-2*01          1  SLLMWITQV  beta
4      CASSAAGADGELFF  TRBV6-5*01  TRBJ2-2*01          1  SLLMWITQV  beta

Public+specific TRB clonotypes (preview):

         cdr3_beta       v_beta      j_beta  n_studies    epitope chain
0     CAASTGIYGYTF    TRBV19*01  TRBJ1-2*01          2  GILGFVFTL  beta
1    CACSGTEDQPQHF    TRBV30*01  TRBJ1-5*01          2  GILGFVFTL  beta
2     CACSQGSYGYTF    TRBV19*01  TRBJ1-2*01          2  GILGFVFTL  beta
3  CAIKLRGSEGDTQYF    TRBV28*01  TRBJ2-3*01          2  GILGFVFTL  beta
4    CAILGYGSTEAFF  TRBV12-3*01  TRBJ1-1*01          2  GILGFVFTL  beta

In [17]:
# alpha: specific + public
specific_tra, public_tra, top10_tra = topN_specific_and_public(df, chain="TRA", min_studies=2, n_epi=20)

print("Top epitopes (TRA) by #unique clonotypes:")
display(top10_tra.rename("n_unique_clonotypes").to_frame())

print("Specific TRA clonotypes (preview):")
display(specific_tra.head())

print("Public+specific TRA clonotypes (preview):")
display(public_tra.head())

Top epitopes (TRA) by #unique clonotypes:

                 n_unique_clonotypes
antigen_epitope
KLGGALQAK                      12112
GILGFVFTL                       4653
NLVPMVATV                       2355
AVFDRKSDAK                      1583
RAKFKQLL                         944
YLQPRTFLL                        661
IVTDFSVIK                        528
LLAGIGTVPI                       411
RLRAEAQVK                        401
GLCTLVAML                        376
TTDPSFLGRY                       373
SPRWYFYYL                        373
LLLGIGILV                        359
ELAGIGILTV                       354
SSLENFRAYV                       286
LLWNGPMAV                        266
SSYRRPVGI                        253
VMATRRNVL                        253
ASNENMETM                        243
CINGVCWTV                        237

Specific TRA clonotypes (preview):

        cdr3_alpha      v_alpha    j_alpha  n_studies    epitope  chain
0   CAAAAYNQGGKLIF   TRAV1-1*01  TRAJ23*01          1  KLGGALQAK  alpha
1  CAAAFSGGGADGLTF  TRAV13-1*01  TRAJ45*01          1  KLGGALQAK  alpha
2    CAAAGAGSYQLTF   TRAV8-1*01  TRAJ28*01          1  KLGGALQAK  alpha
3     CAAAGGGNKLTF  TRAV38-1*01  TRAJ10*01          1  KLGGALQAK  alpha
4   CAAAGGTSYGKLTF    TRAV41*01  TRAJ52*01          1  KLGGALQAK  alpha

Public+specific TRA clonotypes (preview):

         cdr3_alpha      v_alpha    j_alpha  n_studies    epitope  chain
0        CAAANEKLTF   TRAV8-4*01  TRAJ48*01          2  GILGFVFTL  alpha
1    CAAAYGGSQGNLIF    TRAV25*01  TRAJ42*01          2  GILGFVFTL  alpha
2  CAAFPGGETSGSRLTF  TRAV13-1*01     TRAJ58          2  GILGFVFTL  alpha
3      CAAGDSNYQLIW     TRAV3*01  TRAJ33*01          2  GILGFVFTL  alpha
4      CAAGGSQGNLIF    TRAV21*01  TRAJ42*01          2  GILGFVFTL  alpha

In [19]:
public_tra

           cdr3_alpha      v_alpha    j_alpha  n_studies    epitope  chain
0          CAAANEKLTF   TRAV8-4*01  TRAJ48*01          2  GILGFVFTL  alpha
1      CAAAYGGSQGNLIF    TRAV25*01  TRAJ42*01          2  GILGFVFTL  alpha
2    CAAFPGGETSGSRLTF  TRAV13-1*01     TRAJ58          2  GILGFVFTL  alpha
3        CAAGDSNYQLIW     TRAV3*01  TRAJ33*01          2  GILGFVFTL  alpha
4        CAAGGSQGNLIF    TRAV21*01  TRAJ42*01          2  GILGFVFTL  alpha
..                ...          ...        ...        ...        ...    ...
975      CAVNSDGQKLLF  TRAV12-2*01     TRAJ16          2  LLWNGPMAV  alpha
976        CAVSDDKIIF  TRAV12-2*01  TRAJ30*01          2  LLWNGPMAV  alpha
977        CAVSNARLMF  TRAV12-2*01  TRAJ31*01          2  LLWNGPMAV  alpha
978       CAVSSTDKLIF  TRAV12-2*01  TRAJ34*01          2  LLWNGPMAV  alpha
979        CAVTDDKIIF  TRAV12-2*01  TRAJ30*01          2  LLWNGPMAV  alpha

[980 rows x 6 columns]

In [24]:
public_tra.epitope.value_counts()

epitope
GILGFVFTL     870
YLQPRTFLL      45
GLCTLVAML      19
RAKFKQLL       12
NLVPMVATV      12
LLWNGPMAV       9
TTDPSFLGRY      8
SPRWYFYYL       4
ELAGIGILTV      1
Name: count, dtype: int64

In [25]:
from pathlib import Path

outdir = Path("../../data")
outdir.mkdir(parents=True, exist_ok=True)

public_trb.to_csv(outdir / "vdjdb_public_TRB_minStudies2.tsv", sep="\t", index=False)

public_tra.to_csv(outdir / "vdjdb_public_TRA_minStudies2.tsv", sep="\t", index=False)

print("Saved outputs to:", outdir.resolve())

Saved outputs to: /home/evlasova/tcrempnet/data