In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/vdjdb_full_filtered.txt', sep='\t')

/scratch/ipykernel_975234/3455155727.py:1: DtypeWarning: Columns (5,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/vdjdb_full_filtered.txt', sep='\t')

In [22]:
df.columns

Index(['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'd.beta',
       'j.beta', 'species', 'mhc.a', 'mhc.b', 'mhc.class', 'antigen.epitope',
       'antigen.gene', 'antigen.species', 'reference.id',
       'method.identification', 'method.frequency', 'method.singlecell',
       'method.sequencing', 'method.verification', 'meta.study.id',
       'meta.cell.subset', 'meta.subject.cohort', 'meta.subject.id',
       'meta.replica.id', 'meta.clone.id', 'meta.epitope.id', 'meta.tissue',
       'meta.donor.MHC', 'meta.donor.MHC.method', 'meta.structure.id',
       'cdr3fix.alpha', 'cdr3fix.beta', 'vdjdb.score'],
      dtype='object')

In [23]:
df['antigen.epitope'].value_counts()

antigen.epitope
SLLMWITQV    29699
KLGGALQAK    13726
GILGFVFTL    13539
NLVPMVATV     7158
GLCTLVAML     3339
             ...
KMGVTYEM         1
FMGVTYEM         1
LMDMHNGQL        1
RLDAMNGQL        1
RMDYNNMQM        1
Name: count, Length: 1711, dtype: int64

In [24]:
col_mapping = {x: x.replace('.', '_') for x in df.columns}
df = df.rename(columns=col_mapping)

In [25]:
df[df['antigen_epitope'] == 'GILGFVFTL']['reference_id'].value_counts()

reference_id
PMID:28423320                                                                                                                                                                  3985
PMID:37749325                                                                                                                                                                  3409
PMID:40694338                                                                                                                                                                  1887
https://www.10xgenomics.com/resources/application-notes/a-new-way-of-exploring-immunity-linking-highly-multiplexed-antigen-recognition-to-immune-repertoire-and-phenotype/#    1328
PMID:25609818                                                                                                                                                                   843
PMID:34811538                                                                                                                                                                   616
PMID:28636589                                                                                                                                                                   422
PMID:28636592                                                                                                                                                                   255
PMID:28250417                                                                                                                                                                   194
PMID:34793243                                                                                                                                                                   141
PMID:29997621                                                                                                                                                                   133
PMID:29483513                                                                                                                                                                   121
PMID:28629751                                                                                                                                                                    83
PMID:27645996                                                                                                                                                                    43
PMID:7807026                                                                                                                                                                     39
PMID:25339770                                                                                                                                                                    17
PMID:25801351                                                                                                                                                                    16
https://github.com/antigenomics/vdjdb-db/issues/215                                                                                                                               2
PMID:18275829                                                                                                                                                                     2
PMID:21562156                                                                                                                                                                     1
PMID:12796775                                                                                                                                                                     1
PMID:28931605                                                                                                                                                                     1
Name: count, dtype: int64

In [46]:
df.meta_study_id

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
107954    NaN
107955    NaN
107956    NaN
107957    NaN
107958    NaN
Name: meta_study_id, Length: 107959, dtype: object

In [26]:
df.columns

Index(['cdr3_alpha', 'v_alpha', 'j_alpha', 'cdr3_beta', 'v_beta', 'd_beta',
       'j_beta', 'species', 'mhc_a', 'mhc_b', 'mhc_class', 'antigen_epitope',
       'antigen_gene', 'antigen_species', 'reference_id',
       'method_identification', 'method_frequency', 'method_singlecell',
       'method_sequencing', 'method_verification', 'meta_study_id',
       'meta_cell_subset', 'meta_subject_cohort', 'meta_subject_id',
       'meta_replica_id', 'meta_clone_id', 'meta_epitope_id', 'meta_tissue',
       'meta_donor_MHC', 'meta_donor_MHC_method', 'meta_structure_id',
       'cdr3fix_alpha', 'cdr3fix_beta', 'vdjdb_score'],
      dtype='object')

In [44]:
df[(df.antigen_epitope == 'GILGFVFTL') & (df.cdr3_beta.notna())].groupby(['cdr3_beta', 'v_beta', 'd_beta',
       'j_beta']).count()[['study_id']].sort_values('study_id', ascending=False)

KeyError: "None of [Index(['study_id'], dtype='object')] are in the [columns]"

In [ ]:
df[]

In [32]:
df[df.cdr3_beta == 'CASSWGGGSHYGYTF']['antigen_epitope'].value_counts()

antigen_epitope
IVTDFSVIK     130
RAKFKQLL        9
GILGFVFTL       7
AVFDRKSDAK      2
KLGGALQAK       2
Name: count, dtype: int64

In [39]:
df[df.cdr3_beta == 'CASSWGGGSHYGYTF'].groupby(['reference_id', 'antigen_epitope']).nunique()

                                                                    cdr3_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                2
                                                   GILGFVFTL                 6
                                                   IVTDFSVIK               124
                                                   KLGGALQAK                 2
                                                   RAKFKQLL                  8

                                                                    v_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK             2
                                                   GILGFVFTL              5
                                                   IVTDFSVIK             39
                                                   KLGGALQAK              2
                                                   RAKFKQLL               6

                                                                    j_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK             2
                                                   GILGFVFTL              3
                                                   IVTDFSVIK             42
                                                   KLGGALQAK              2
                                                   RAKFKQLL               7

                                                                    cdr3_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK               1
                                                   GILGFVFTL                1
                                                   IVTDFSVIK                1
                                                   KLGGALQAK                1
                                                   RAKFKQLL                 1

                                                                    v_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK            1
                                                   GILGFVFTL             2
                                                   IVTDFSVIK             2
                                                   KLGGALQAK             1
                                                   RAKFKQLL              2

                                                                    d_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK            1
                                                   GILGFVFTL             1
                                                   IVTDFSVIK             1
                                                   KLGGALQAK             1
                                                   RAKFKQLL              1

                                                                    j_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK            1
                                                   GILGFVFTL             1
                                                   IVTDFSVIK             1
                                                   KLGGALQAK             1
                                                   RAKFKQLL              1

                                                                    species  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK             1
                                                   GILGFVFTL              1
                                                   IVTDFSVIK              1
                                                   KLGGALQAK              1
                                                   RAKFKQLL               1

                                                                    mhc_a  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK           1
                                                   GILGFVFTL            1
                                                   IVTDFSVIK            1
                                                   KLGGALQAK            1
                                                   RAKFKQLL             1

                                                                    mhc_b  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK           1
                                                   GILGFVFTL            1
                                                   IVTDFSVIK            1
                                                   KLGGALQAK            1
                                                   RAKFKQLL             1

                                                                    ...  \
reference_id                                       antigen_epitope  ...
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK       ...
                                                   GILGFVFTL        ...
                                                   IVTDFSVIK        ...
                                                   KLGGALQAK        ...
                                                   RAKFKQLL         ...

                                                                    meta_replica_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                     0
                                                   GILGFVFTL                      0
                                                   IVTDFSVIK                      0
                                                   KLGGALQAK                      0
                                                   RAKFKQLL                       0

                                                                    meta_clone_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                   0
                                                   GILGFVFTL                    0
                                                   IVTDFSVIK                    0
                                                   KLGGALQAK                    0
                                                   RAKFKQLL                     0

                                                                    meta_epitope_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                     0
                                                   GILGFVFTL                      0
                                                   IVTDFSVIK                      0
                                                   KLGGALQAK                      0
                                                   RAKFKQLL                       0

                                                                    meta_tissue  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                 0
                                                   GILGFVFTL                  0
                                                   IVTDFSVIK                  0
                                                   KLGGALQAK                  0
                                                   RAKFKQLL                   0

                                                                    meta_donor_MHC  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                    0
                                                   GILGFVFTL                     0
                                                   IVTDFSVIK                     0
                                                   KLGGALQAK                     0
                                                   RAKFKQLL                      0

                                                                    meta_donor_MHC_method  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                           0
                                                   GILGFVFTL                            0
                                                   IVTDFSVIK                            0
                                                   KLGGALQAK                            0
                                                   RAKFKQLL                             0

                                                                    meta_structure_id  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                       0
                                                   GILGFVFTL                        0
                                                   IVTDFSVIK                        0
                                                   KLGGALQAK                        0
                                                   RAKFKQLL                         0

                                                                    cdr3fix_alpha  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                   2
                                                   GILGFVFTL                    6
                                                   IVTDFSVIK                  124
                                                   KLGGALQAK                    2
                                                   RAKFKQLL                     8

                                                                    cdr3fix_beta  \
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                  1
                                                   GILGFVFTL                   2
                                                   IVTDFSVIK                   2
                                                   KLGGALQAK                   1
                                                   RAKFKQLL                    2

                                                                    vdjdb_score
reference_id                                       antigen_epitope
https://www.10xgenomics.com/resources/applicati... AVFDRKSDAK                 1
                                                   GILGFVFTL                  1
                                                   IVTDFSVIK                  2
                                                   KLGGALQAK                  1
                                                   RAKFKQLL                   1

[5 rows x 32 columns]

In [99]:
import pandas as pd

def get_public_epitope_specific_clonotypes(
    df: pd.DataFrame,
    epitope: str,
    chain: str = "beta",
    min_studies: int = 2,
):
    """
    Клонотипы, которые:
      • встречаются >= min_studies исследований
      • во всём датасете ассоциированы только с данным эпитопом
    """

    # --- колонки для цепи ---
    cdr3 = f"cdr3_{chain}"
    v = f"v_{chain}"
    j = f"j_{chain}"

    clonotype_cols = [cdr3, v, j]

    # --- только строки с эпитопом ---
    df_annot = df[df["antigen_epitope"].notna()]

    # --- набор эпитопов на клонотип ---
    epi_sets = (
        df_annot
        .groupby(clonotype_cols)["antigen_epitope"]
        .agg(lambda x: set(x))
    )

    # --- оставляем только те, где эпитоп один и он нужный ---
    specific = epi_sets[epi_sets == {epitope}].index
    
    # --- строки с этим эпитопом ---
    df_target = df[df["antigen_epitope"] == epitope]

    # --- число исследований ---
    study_counts = (
        df_target
        .set_index(clonotype_cols)
        .loc[specific]
        .reset_index()
        .groupby(clonotype_cols)["reference_id"]
        .nunique()
    )

    public = study_counts[study_counts >= min_studies].reset_index()
    public['epitope'] = epitope

    return public

In [100]:
hits = get_public_epitope_specific_clonotypes(
    df,
    epitope="GILGFVFTL",
    chain="beta",
    min_studies=2
)

hits

             cdr3_beta       v_beta      j_beta  reference_id    epitope
0         CAASTGIYGYTF    TRBV19*01  TRBJ1-2*01             2  GILGFVFTL
1        CACSGTEDQPQHF    TRBV30*01  TRBJ1-5*01             2  GILGFVFTL
2         CACSQGSYGYTF    TRBV19*01  TRBJ1-2*01             2  GILGFVFTL
3      CAIKLRGSEGDTQYF    TRBV28*01  TRBJ2-3*01             2  GILGFVFTL
4        CAILGYGSTEAFF  TRBV12-3*01  TRBJ1-1*01             2  GILGFVFTL
...                ...          ...         ...           ...        ...
1100     CSVGEGGYTEAFF  TRBV29-1*01  TRBJ1-1*01             2  GILGFVFTL
1101        CSVITDTQYF  TRBV29-1*01  TRBJ2-3*01             2  GILGFVFTL
1102  CSVSTLLRGFNYGYTF  TRBV20-1*01  TRBJ1-2*01             2  GILGFVFTL
1103    CSVVASGNPDTQYF  TRBV29-1*01  TRBJ2-3*01             2  GILGFVFTL
1104     CSVVSRDSYEQYF  TRBV29-1*01  TRBJ2-7*01             2  GILGFVFTL

[1105 rows x 5 columns]

In [106]:
def top10_public_specific(df, chain="beta", min_studies=2, n_epi=20):

    cols = [f"cdr3_{chain}", f"v_{chain}", f"j_{chain}"]
    if chain == "beta" and f"d_{chain}" in df.columns:
        cols.append(f"d_{chain}")

    # --- считаем уникальные клонотипы на эпитоп ---
    uniq = (
        df[df["antigen_epitope"].notna()]
        .drop_duplicates(subset=["antigen_epitope"] + cols)
        .groupby("antigen_epitope")
        .size()
        .sort_values(ascending=False)
    )

    top_epitopes = uniq.head(n_epi).index

    # --- собираем результаты ---
    parts = [
        get_public_epitope_specific_clonotypes(df, ep, chain, min_studies)
        for ep in top_epitopes
    ]

    return pd.concat(parts, ignore_index=True), uniq.head(n_epi)

In [107]:
# запуск
clono_df, top10 = top10_public_specific(df, chain="beta", min_studies=2)

print("Top-10 epitopes by #unique clonotypes:")
display(top10.rename("n_unique_clonotypes").to_frame())


# --- считаем общее число клонотипов на эпитоп ---
chain = "beta"
cols = [f"cdr3_{chain}", f"v_{chain}", f"j_{chain}"]
if chain == "beta" and f"d_{chain}" in df.columns:
    cols.append(f"d_{chain}")

total_clono = (
    df[df["antigen_epitope"].notna()]
    .drop_duplicates(subset=["antigen_epitope"] + cols)
    .groupby("antigen_epitope")
    .size()
    .rename("n_total_clonotypes")
)

public_clono = (
    clono_df.groupby("epitope")
    .size()
    .rename("n_public_specific_clonotypes")
)

summary = (
    pd.concat([total_clono, public_clono], axis=1)
    .fillna(0)
    .astype(int)
)

summary["fraction_public_specific"] = (
    summary["n_public_specific_clonotypes"] /
    summary["n_total_clonotypes"]
)

summary = summary.loc[top10.index].sort_values(
    "n_public_specific_clonotypes", ascending=False
)

print("\nPublic+specific clonotypes summary:")
display(summary)


# --- топ клонотипов на эпитоп ---
K = 15
for ep in top10.index:
    sub = clono_df[clono_df["epitope"] == ep].copy()

    print(
        f"\n=== {ep} | public+specific: {len(sub)} "
        f"/ total: {summary.loc[ep, 'n_total_clonotypes']} ==="
    )

    if len(sub) == 0:
        continue

    display(sub.head(K))

Top-10 epitopes by #unique clonotypes:

                 n_unique_clonotypes
antigen_epitope
SLLMWITQV                      29697
KLGGALQAK                      12562
GILGFVFTL                       5356
NLVPMVATV                       4689
AVFDRKSDAK                      1619
ELAGIGILTV                      1495
RAKFKQLL                        1374
GLCTLVAML                       1232
YLQPRTFLL                        952
LLAGIGTVPI                       832
IVTDFSVIK                        546
CTPYDINQM                        544
TTPESANL                         534
SPRWYFYYL                        525
KRWIILGLNK                       462
TFEYVSQPFLMDLE                   447
TTDPSFLGRY                       422
YVLDHLIVV                        421
LLWNGPMAV                        408
RLRAEAQVK                        405

Public+specific clonotypes summary:

,n_total_clonotypes,n_public_specific_clonotypes,fraction_public_specific
antigen_epitope,,,
GILGFVFTL,5356,1105,0.206311
RAKFKQLL,1374,62,0.045124
GLCTLVAML,1232,59,0.047890
NLVPMVATV,4689,57,0.012156
YLQPRTFLL,952,46,0.048319
KRWIILGLNK,462,31,0.067100
YVLDHLIVV,421,20,0.047506
ELAGIGILTV,1495,6,0.004013
AVFDRKSDAK,1619,5,0.003088
IVTDFSVIK,546,4,0.007326
TFEYVSQPFLMDLE,447,3,0.006711
CTPYDINQM,544,3,0.005515
SPRWYFYYL,525,2,0.003810
LLWNGPMAV,408,1,0.002451
TTDPSFLGRY,422,1,0.002370
KLGGALQAK,12562,0,0.000000
SLLMWITQV,29697,0,0.000000
LLAGIGTVPI,832,0,0.000000
TTPESANL,534,0,0.000000
RLRAEAQVK,405,0,0.000000

=== SLLMWITQV | public+specific: 0 / total: 29697 ===

=== KLGGALQAK | public+specific: 0 / total: 12562 ===

=== GILGFVFTL | public+specific: 1105 / total: 5356 ===

           cdr3_beta       v_beta      j_beta  reference_id    epitope
0       CAASTGIYGYTF    TRBV19*01  TRBJ1-2*01             2  GILGFVFTL
1      CACSGTEDQPQHF    TRBV30*01  TRBJ1-5*01             2  GILGFVFTL
2       CACSQGSYGYTF    TRBV19*01  TRBJ1-2*01             2  GILGFVFTL
3    CAIKLRGSEGDTQYF    TRBV28*01  TRBJ2-3*01             2  GILGFVFTL
4      CAILGYGSTEAFF  TRBV12-3*01  TRBJ1-1*01             2  GILGFVFTL
5    CAIQTGWDFWDGYTF   TRBV6-1*01  TRBJ1-2*01             2  GILGFVFTL
6       CAISEDRETQYF  TRBV10-3*01  TRBJ2-5*01             2  GILGFVFTL
7   CAISEGQGSYNSPLHF  TRBV10-3*01  TRBJ1-6*01             2  GILGFVFTL
8    CAISGGDRANYGYTF  TRBV10-3*01  TRBJ1-2*01             2  GILGFVFTL
9     CAISGGQGRREQFF    TRBV28*01  TRBJ2-1*01             2  GILGFVFTL
10      CAISQNIDEQFF  TRBV10-3*01  TRBJ2-1*01             2  GILGFVFTL
11    CALQGEVLNTEAFF    TRBV30*01  TRBJ1-1*01             2  GILGFVFTL
12    CALVVSGPTGELFF    TRBV19*01  TRBJ2-2*01             2  GILGFVFTL
13      CARRGGSYEQYF   TRBV6-4*01  TRBJ2-7*01             2  GILGFVFTL
14      CASAAGTYGYTF    TRBV19*01  TRBJ1-2*01             2  GILGFVFTL

=== NLVPMVATV | public+specific: 57 / total: 4689 ===

              cdr3_beta       v_beta      j_beta  reference_id    epitope
1105     CAASREGPNQPQHF    TRBV15*01  TRBJ1-5*01             2  NLVPMVATV
1106   CAGSKQSGTGYYGYTF   TRBV6-5*01  TRBJ1-2*01             2  NLVPMVATV
1107    CAGSQVWGSDEKLFF   TRBV3-1*01  TRBJ1-4*01             2  NLVPMVATV
1108       CASASANYGYTF  TRBV12-4*01  TRBJ1-2*01             2  NLVPMVATV
1109    CASRALAGGQVEQFF   TRBV6-5*01  TRBJ2-1*01             2  NLVPMVATV
1110    CASRGLAGGLGELFF   TRBV6-5*01  TRBJ2-2*01             2  NLVPMVATV
1111   CASRSAQRGFTETQYF    TRBV28*01  TRBJ2-5*01             2  NLVPMVATV
1112   CASSALGGAGTGELFF     TRBV9*01  TRBJ2-2*01             2  NLVPMVATV
1113    CASSAQTGASYGYTF   TRBV6-5*01  TRBJ1-2*01             2  NLVPMVATV
1114    CASSAVAGAPLEQYF    TRBV27*01  TRBJ2-7*01             2  NLVPMVATV
1115    CASSCQTGAACGYTF   TRBV6-5*01  TRBJ1-2*01             3  NLVPMVATV
1116   CASSEEPSGGAYEQYF   TRBV6-1*01  TRBJ2-7*01             2  NLVPMVATV
1117    CASSETGFGNQPQHF  TRBV25-1*01  TRBJ1-5*01             2  NLVPMVATV
1118      CASSFQGYTEAFF    TRBV28*01  TRBJ1-1*01             4  NLVPMVATV
1119  CASSHWDRETSGNTIYF   TRBV6-6*01  TRBJ1-3*01             2  NLVPMVATV

=== AVFDRKSDAK | public+specific: 5 / total: 1619 ===

            cdr3_beta      v_beta      j_beta  reference_id     epitope
1162     CASGWGSQPQHF  TRBV7-9*01  TRBJ1-5*01             2  AVFDRKSDAK
1163   CASSLTSAAGELFF   TRBV28*01  TRBJ2-2*01             2  AVFDRKSDAK
1164   CASSLTSATGELFF   TRBV28*01  TRBJ2-2*01             3  AVFDRKSDAK
1165  CASSQEGTGSYEQYF  TRBV6-2*01  TRBJ2-7*01             2  AVFDRKSDAK
1166   CASSRTSATGELFF   TRBV28*01  TRBJ2-2*01             3  AVFDRKSDAK

=== ELAGIGILTV | public+specific: 6 / total: 1495 ===

             cdr3_beta     v_beta      j_beta  reference_id     epitope
1167    CASSFQGLGQPQHF  TRBV28*01  TRBJ1-5*01             2  ELAGIGILTV
1168   CASSFSSGSPHEQFF  TRBV27*01  TRBJ2-1*01             2  ELAGIGILTV
1169    CASSPGALNTEAFF  TRBV19*01  TRBJ1-1*01             2  ELAGIGILTV
1170   CASSQGLAGAGELFF  TRBV19*01  TRBJ2-2*01             2  ELAGIGILTV
1171  CASSSSGTSGVYEQYF  TRBV28*01  TRBJ2-7*01             2  ELAGIGILTV
1172    CASTLTGLGQPQHF  TRBV28*01  TRBJ1-5*01             2  ELAGIGILTV

=== RAKFKQLL | public+specific: 62 / total: 1374 ===

             cdr3_beta       v_beta      j_beta  reference_id   epitope
1173  CAGRPRLAGGNNEQFF    TRBV28*01  TRBJ2-1*01             2  RAKFKQLL
1174    CASKMRGDVYEQYF    TRBV18*01  TRBJ2-7*01             2  RAKFKQLL
1175  CASLFTGTSPTDTQYF  TRBV12-3*01  TRBJ2-3*01             2  RAKFKQLL
1176    CASLRGLGTDTQYF   TRBV7-9*01  TRBJ2-3*01             2  RAKFKQLL
1177      CASSDLNSPLHF    TRBV27*01  TRBJ1-6*01             3  RAKFKQLL
1178    CASSFQGSNEKLFF    TRBV28*01  TRBJ1-4*01             2  RAKFKQLL
1179   CASSFSGSLTTEAFF  TRBV12-3*01  TRBJ1-1*01             2  RAKFKQLL
1180   CASSKQGRGTDTQYF   TRBV7-9*01  TRBJ2-3*01             2  RAKFKQLL
1181     CASSLAPSYEQYF   TRBV7-9*01  TRBJ2-7*01             2  RAKFKQLL
1182  CASSLAVLSSYNEQFF   TRBV7-3*01  TRBJ2-1*01             2  RAKFKQLL
1183     CASSLEGSYEQYF    TRBV28*01  TRBJ2-7*01             2  RAKFKQLL
1184     CASSLGGTNEQFF   TRBV4-1*01  TRBJ2-1*01             2  RAKFKQLL
1185   CASSLGLGVNNEQFF   TRBV7-9*01  TRBJ2-1*01             2  RAKFKQLL
1186  CASSLIASGGYNEQFF   TRBV7-3*01  TRBJ2-1*01             3  RAKFKQLL
1187    CASSLIRGTGELFF   TRBV3-1*01  TRBJ2-2*01             2  RAKFKQLL

=== GLCTLVAML | public+specific: 59 / total: 1232 ===

             cdr3_beta       v_beta      j_beta  reference_id    epitope
1235   CAGGTGETSPGELFF     TRBV2*01  TRBJ2-2*01             2  GLCTLVAML
1236   CASSEGNVAPGELFF     TRBV2*01  TRBJ2-2*01             2  GLCTLVAML
1237   CASSEGRVAPGEQYF     TRBV2*01  TRBJ2-7*01             2  GLCTLVAML
1238   CASSEGRVLPGELFF     TRBV2*01  TRBJ2-2*01             2  GLCTLVAML
1239   CASSEGRVSPGELFF     TRBV2*01  TRBJ2-2*01             2  GLCTLVAML
1240     CASSFGQQETQYF  TRBV12-4*01  TRBJ2-5*01             2  GLCTLVAML
1241   CASSFSSGTTDTQYF  TRBV11-2*01  TRBJ2-3*01             4  GLCTLVAML
1242    CASSIDGTAYEQYF    TRBV19*01  TRBJ2-7*01             3  GLCTLVAML
1243     CASSLGLENEQFF   TRBV7-8*01  TRBJ2-1*01             2  GLCTLVAML
1244  CASSPGQLSNTGELFF     TRBV9*01  TRBJ2-2*01             2  GLCTLVAML
1245   CASSPTSGSIYEQYF   TRBV3-1*01  TRBJ2-7*01             4  GLCTLVAML
1246  CASSQAGLAAYNEQFF   TRBV4-2*01  TRBJ2-1*01             2  GLCTLVAML
1247  CASSQDGAGGLGEQFF   TRBV4-2*01  TRBJ2-1*01             2  GLCTLVAML
1248  CASSQDSSGGLGEQFF   TRBV4-2*01  TRBJ2-1*01             3  GLCTLVAML
1249     CASSQSPGDTQYF    TRBV14*01  TRBJ2-3*01             2  GLCTLVAML

=== YLQPRTFLL | public+specific: 46 / total: 952 ===

          cdr3_beta       v_beta      j_beta  reference_id    epitope
1294  CAGQVTNTGELFF    TRBV19*01  TRBJ2-2*01             2  YLQPRTFLL
1295  CARGLADTGELFF   TRBV7-9*01  TRBJ2-2*01             2  YLQPRTFLL
1296  CASGDENTGELFF   TRBV5-1*01  TRBJ2-2*01             3  YLQPRTFLL
1297  CASGEANTGELFF  TRBV12-3*01  TRBJ2-2*01             2  YLQPRTFLL
1298  CASGEGNTGELFF   TRBV7-9*01  TRBJ2-2*01             3  YLQPRTFLL
1299  CASGGTNTGELFF     TRBV2*01  TRBJ2-2*01             4  YLQPRTFLL
1300  CASMEENTGELFF   TRBV5-1*01  TRBJ2-2*01             2  YLQPRTFLL
1301  CASNDLNTGELFF     TRBV2*01  TRBJ2-2*01             2  YLQPRTFLL
1302  CASNEENTGELFF   TRBV5-1*01  TRBJ2-2*01             2  YLQPRTFLL
1303  CASQDRNTGELFF     TRBV2*01  TRBJ2-2*01             2  YLQPRTFLL
1304  CASQEANTGELFF    TRBV19*01  TRBJ2-2*01             2  YLQPRTFLL
1305  CASQGLNTGELFF    TRBV15*01  TRBJ2-2*01             2  YLQPRTFLL
1306  CASQILNTGELFF    TRBV19*01  TRBJ2-2*01             2  YLQPRTFLL
1307  CASSDLDTGELFF     TRBV2*01  TRBJ2-2*01             5  YLQPRTFLL
1308  CASSDLNTGELFF     TRBV2*01  TRBJ2-2*01             3  YLQPRTFLL

=== LLAGIGTVPI | public+specific: 0 / total: 832 ===

=== IVTDFSVIK | public+specific: 4 / total: 546 ===

             cdr3_beta      v_beta      j_beta  reference_id    epitope
1340   CASREGDINTGELFF    TRBV9*01  TRBJ2-2*01             2  IVTDFSVIK
1341  CASSEASGGFYNEQFF    TRBV2*01  TRBJ2-1*01             2  IVTDFSVIK
1342    CASSIVGAHTEAFF   TRBV19*01  TRBJ1-1*01             2  IVTDFSVIK
1343   CASSWGQGSNYGYTF  TRBV7-2*01  TRBJ1-2*01             2  IVTDFSVIK

=== CTPYDINQM | public+specific: 3 / total: 544 ===

             cdr3_beta       v_beta      j_beta  reference_id    epitope
1344   CASSGTGNSNQPQYF  TRBV12-3*01  TRBJ1-5*01             2  CTPYDINQM
1345  CASSQGPGNSNQPQYF     TRBV9*01  TRBJ1-5*01             2  CTPYDINQM
1346   CASSVAGNSNQPQYF  TRBV12-3*01  TRBJ1-5*01             2  CTPYDINQM

=== TTPESANL | public+specific: 0 / total: 534 ===

=== SPRWYFYYL | public+specific: 2 / total: 525 ===

            cdr3_beta       v_beta      j_beta  reference_id    epitope
1347  CASSQEWTGRTEAFF   TRBV4-1*01  TRBJ1-1*01             2  SPRWYFYYL
1348    CATSDLTQDTQYF  TRBV24-1*01  TRBJ2-3*01             2  SPRWYFYYL

=== KRWIILGLNK | public+specific: 31 / total: 462 ===

              cdr3_beta       v_beta      j_beta  reference_id     epitope
1349     CASATGIFNNEQFF   TRBV4-3*01  TRBJ2-1*01             2  KRWIILGLNK
1350       CASGFGGTEAFF  TRBV12-5*01  TRBJ1-1*01             2  KRWIILGLNK
1351     CASKNRPTGNTIYF     TRBV21-1  TRBJ1-3*01             2  KRWIILGLNK
1352     CASSAGISAYEQYF   TRBV4-3*01  TRBJ2-7*01             2  KRWIILGLNK
1353       CASSAQTGFLFF    TRBV27*01  TRBJ1-4*01             2  KRWIILGLNK
1354       CASSLDSYEQYF   TRBV7-9*01  TRBJ2-7*01             3  KRWIILGLNK
1355   CASSLGLAGTHNEQFF    TRBV28*01  TRBJ2-1*01             2  KRWIILGLNK
1356  CASSPDVGGAFFYGYTF   TRBV5-1*01  TRBJ1-2*01             2  KRWIILGLNK
1357     CASSPGLSGNTIYF   TRBV4-3*01  TRBJ1-3*01             2  KRWIILGLNK
1358     CASSPGQFAYEQYF   TRBV6-5*01  TRBJ2-7*01             2  KRWIILGLNK
1359     CASSPGQLGNTIYF   TRBV4-3*01  TRBJ1-3*01             3  KRWIILGLNK
1360     CASSPGQVAYEQYF   TRBV4-3*01  TRBJ2-7*01             2  KRWIILGLNK
1361     CASSPGRLSHEQFF   TRBV4-3*01  TRBJ2-1*01             2  KRWIILGLNK
1362       CASSPRTGELFF    TRBV27*01  TRBJ2-2*01             3  KRWIILGLNK
1363     CASSQGQFGNEQFF   TRBV4-3*01  TRBJ2-1*01             2  KRWIILGLNK

=== TFEYVSQPFLMDLE | public+specific: 3 / total: 447 ===

             cdr3_beta      v_beta      j_beta  reference_id         epitope
1380     CASSPRGGHGYTF   TRBV14*01  TRBJ1-2*01             2  TFEYVSQPFLMDLE
1381  CASSPRSSANTGELFF    TRBV9*01  TRBJ2-2*01             2  TFEYVSQPFLMDLE
1382     CASSYRGDYGYTF  TRBV6-2*01  TRBJ1-2*01             2  TFEYVSQPFLMDLE

=== TTDPSFLGRY | public+specific: 1 / total: 422 ===

           cdr3_beta     v_beta      j_beta  reference_id     epitope
1383  CASSWTSGSYEQYF  TRBV28*01  TRBJ2-7*01             2  TTDPSFLGRY

=== YVLDHLIVV | public+specific: 20 / total: 421 ===

             cdr3_beta       v_beta      j_beta  reference_id    epitope
1384    CASMGGASYNEQFF    TRBV19*01  TRBJ2-1*01             2  YVLDHLIVV
1385   CASRALLGSNQPQHF    TRBV19*01  TRBJ1-5*01             2  YVLDHLIVV
1386   CASRGLLGGITEAFF    TRBV19*01  TRBJ1-1*01             2  YVLDHLIVV
1387      CASSAGPDTQYF  TRBV10-1*01  TRBJ2-3*01             2  YVLDHLIVV
1388      CASSDLANEQFF  TRBV10-1*01  TRBJ2-1*01             2  YVLDHLIVV
1389      CASSLFSNEQFF    TRBV28*01  TRBJ2-1*01             2  YVLDHLIVV
1390  CASSLGTSFRTDTQYF  TRBV12-3*01  TRBJ2-3*01             2  YVLDHLIVV
1391      CASSLYSDTQYF    TRBV28*01  TRBJ2-3*01             2  YVLDHLIVV
1392   CASSMLLGGGQPQHF    TRBV19*01  TRBJ1-5*01             2  YVLDHLIVV
1393  CASSPSLVGSADTQYF   TRBV3-1*01  TRBJ2-3*01             2  YVLDHLIVV
1394  CASSQTLAGGGETQYF   TRBV3-1*01  TRBJ2-5*01             2  YVLDHLIVV
1395   CASSSLTGSGQPQHF    TRBV28*01  TRBJ1-5*01             2  YVLDHLIVV
1396   CASSSPGDYTYEQYF  TRBV11-2*01  TRBJ2-7*01             2  YVLDHLIVV
1397     CATSDYGEDTQYF  TRBV24-1*01  TRBJ2-3*01             2  YVLDHLIVV
1398     CATSWTGTYEQYF   TRBV6-1*01  TRBJ2-7*01             2  YVLDHLIVV

=== LLWNGPMAV | public+specific: 1 / total: 408 ===

           cdr3_beta    v_beta      j_beta  reference_id    epitope
1404  CASSAGTGAYEQYF  TRBV9*01  TRBJ2-7*01             2  LLWNGPMAV

=== RLRAEAQVK | public+specific: 0 / total: 405 ===

In [109]:
# запуск
clono_df, top10 = top10_public_specific(df, chain="alpha", min_studies=2)

print("Top-10 epitopes by #unique clonotypes:")
display(top10.rename("n_unique_clonotypes").to_frame())


# --- считаем общее число клонотипов на эпитоп ---
chain = "alpha"
cols = [f"cdr3_{chain}", f"v_{chain}", f"j_{chain}"]
if chain == "beta" and f"d_{chain}" in df.columns:
    cols.append(f"d_{chain}")

total_clono = (
    df[df["antigen_epitope"].notna()]
    .drop_duplicates(subset=["antigen_epitope"] + cols)
    .groupby("antigen_epitope")
    .size()
    .rename("n_total_clonotypes")
)

public_clono = (
    clono_df.groupby("epitope")
    .size()
    .rename("n_public_specific_clonotypes")
)

summary = (
    pd.concat([total_clono, public_clono], axis=1)
    .fillna(0)
    .astype(int)
)

summary["fraction_public_specific"] = (
    summary["n_public_specific_clonotypes"] /
    summary["n_total_clonotypes"]
)

summary = summary.loc[top10.index].sort_values(
    "n_public_specific_clonotypes", ascending=False
)

print("\nPublic+specific clonotypes summary:")
display(summary)


# --- топ клонотипов на эпитоп ---
K = 15
for ep in top10.index:
    sub = clono_df[clono_df["epitope"] == ep].copy()

    print(
        f"\n=== {ep} | public+specific: {len(sub)} "
        f"/ total: {summary.loc[ep, 'n_total_clonotypes']} ==="
    )

    if len(sub) == 0:
        continue

    display(sub.head(K))

Top-10 epitopes by #unique clonotypes:

                 n_unique_clonotypes
antigen_epitope
KLGGALQAK                      12112
GILGFVFTL                       4661
NLVPMVATV                       2362
AVFDRKSDAK                      1584
RAKFKQLL                         945
YLQPRTFLL                        662
IVTDFSVIK                        529
LLAGIGTVPI                       412
RLRAEAQVK                        401
GLCTLVAML                        380
TTDPSFLGRY                       374
SPRWYFYYL                        374
LLLGIGILV                        360
ELAGIGILTV                       355
SSLENFRAYV                       286
LLWNGPMAV                        267
VMATRRNVL                        253
SSYRRPVGI                        253
ASNENMETM                        243
CINGVCWTV                        238

Public+specific clonotypes summary:

,n_total_clonotypes,n_public_specific_clonotypes,fraction_public_specific
antigen_epitope,,,
GILGFVFTL,4661,870,0.186655
YLQPRTFLL,662,45,0.067976
GLCTLVAML,380,19,0.050000
NLVPMVATV,2362,12,0.005080
RAKFKQLL,945,12,0.012698
LLWNGPMAV,267,9,0.033708
TTDPSFLGRY,374,8,0.021390
SPRWYFYYL,374,4,0.010695
ELAGIGILTV,355,1,0.002817
KLGGALQAK,12112,0,0.000000
AVFDRKSDAK,1584,0,0.000000
IVTDFSVIK,529,0,0.000000
RLRAEAQVK,401,0,0.000000
LLAGIGTVPI,412,0,0.000000
LLLGIGILV,360,0,0.000000
SSLENFRAYV,286,0,0.000000
VMATRRNVL,253,0,0.000000
SSYRRPVGI,253,0,0.000000
ASNENMETM,243,0,0.000000
CINGVCWTV,238,0,0.000000

=== KLGGALQAK | public+specific: 0 / total: 12112 ===

=== GILGFVFTL | public+specific: 870 / total: 4661 ===

          cdr3_alpha        v_alpha    j_alpha  reference_id    epitope
0         CAAANEKLTF     TRAV8-4*01  TRAJ48*01             2  GILGFVFTL
1     CAAAYGGSQGNLIF      TRAV25*01  TRAJ42*01             2  GILGFVFTL
2   CAAFPGGETSGSRLTF    TRAV13-1*01     TRAJ58             2  GILGFVFTL
3       CAAGDSNYQLIW       TRAV3*01  TRAJ33*01             2  GILGFVFTL
4       CAAGGSQGNLIF      TRAV21*01  TRAJ42*01             2  GILGFVFTL
5       CAAGGSQGNLIF     TRAV8-6*01  TRAJ42*01             2  GILGFVFTL
6    CAAIILTGGGNKLTF    TRAV13-1*01  TRAJ10*01             2  GILGFVFTL
7    CAAILYNNAGNMLTF  TRAV23/DV6*01  TRAJ39*01             2  GILGFVFTL
8     CAAIPGGGSYIPTF    TRAV13-1*01   TRAJ6*01             2  GILGFVFTL
9       CAAISNTGKLIF    TRAV13-1*01  TRAJ37*01             3  GILGFVFTL
10     CAAKGTSYDKVIF  TRAV29/DV5*01  TRAJ50*01             2  GILGFVFTL
11  CAAKYSAEDNDYKLSF  TRAV23/DV6*01  TRAJ20*01             2  GILGFVFTL
12   CAALDRGSTLGRLYF     TRAV8-3*01  TRAJ18*01             2  GILGFVFTL
13    CAALGAGNTGKLIF    TRAV13-1*01  TRAJ37*01             2  GILGFVFTL
14    CAALGGGSQGNLIF    TRAV13-1*01  TRAJ42*01             2  GILGFVFTL

=== NLVPMVATV | public+specific: 12 / total: 2362 ===

           cdr3_alpha        v_alpha    j_alpha  reference_id    epitope
870  CAEIPNYGGSQGNLIF       TRAV5*01  TRAJ42*01             5  NLVPMVATV
871       CAFITGNQFYF      TRAV24*01  TRAJ49*01             2  NLVPMVATV
872        CAFNDYKLSF      TRAV24*01  TRAJ20*01             2  NLVPMVATV
873      CAFPYNNNDMRF      TRAV24*01  TRAJ43*01             2  NLVPMVATV
874    CAGGGSSNTGKLIF     TRAV8-3*01  TRAJ37*01             2  NLVPMVATV
875    CAGHGSSNTGKLIF     TRAV8-3*01  TRAJ37*01             2  NLVPMVATV
876      CAMRGSNYKLTF  TRAV14/DV4*01  TRAJ53*01             2  NLVPMVATV
877       CASNTGNQFYF      TRAV24*01  TRAJ49*01             2  NLVPMVATV
878       CAVAFGNQFYF     TRAV8-3*01  TRAJ49*01             3  NLVPMVATV
879      CAVRDISARLMF       TRAV3*01  TRAJ31*01             5  NLVPMVATV
880      CAVRDTNARLMF       TRAV3*01  TRAJ31*01             3  NLVPMVATV
881       CIRDNNNDMRF    TRAV26-2*01  TRAJ43*01             2  NLVPMVATV

=== AVFDRKSDAK | public+specific: 0 / total: 1584 ===

=== RAKFKQLL | public+specific: 12 / total: 945 ===

          cdr3_alpha      v_alpha    j_alpha  reference_id   epitope
882    CAAEETSYDKVIF  TRAV13-1*01  TRAJ50*01             2  RAKFKQLL
883    CAAVETSYDKVIF  TRAV13-1*01  TRAJ50*01             2  RAKFKQLL
884    CAEGETSYDKVIF     TRAV5*01  TRAJ50*01             2  RAKFKQLL
885    CAETETSYDKVIF  TRAV13-2*01  TRAJ50*01             2  RAKFKQLL
886    CAGAETSYDKVIF  TRAV13-1*01  TRAJ50*01             2  RAKFKQLL
887    CAGGETSYDKVIF  TRAV13-1*01  TRAJ50*01             2  RAKFKQLL
888  CAMSYSGGSNYKLTF  TRAV12-3*01  TRAJ53*01             2  RAKFKQLL
889      CAPWDFNKFYF  TRAV13-1*01  TRAJ21*01             2  RAKFKQLL
890    CILMETSYDKVIF  TRAV26-2*01  TRAJ50*01             2  RAKFKQLL
891    CILTETSYDKVIF  TRAV26-2*01  TRAJ50*01             2  RAKFKQLL
892    CIVRETSYDKVIF  TRAV26-1*01  TRAJ50*01             2  RAKFKQLL
893     CVVNIDNARLMF  TRAV12-1*01  TRAJ31*01             2  RAKFKQLL

=== YLQPRTFLL | public+specific: 45 / total: 662 ===

          cdr3_alpha      v_alpha    j_alpha  reference_id    epitope
894      CAVNEDDKIIF  TRAV12-2*01  TRAJ30*01             2  YLQPRTFLL
895      CAVNGDDKIIF  TRAV12-2*01  TRAJ30*01             2  YLQPRTFLL
896      CAVNMDDKIIF  TRAV12-2*01  TRAJ30*01             2  YLQPRTFLL
897      CVVNAGNMLTF  TRAV12-1*01  TRAJ39*01             2  YLQPRTFLL
898   CVVNAPSGNTPLVF  TRAV12-1*01  TRAJ29*01             3  YLQPRTFLL
899      CVVNDLDDMRF  TRAV12-1*01  TRAJ43*01             2  YLQPRTFLL
900      CVVNDNNDMRF  TRAV12-1*01  TRAJ43*01             2  YLQPRTFLL
901  CVVNDPNSGNTPLVF  TRAV12-1*01  TRAJ29*01             2  YLQPRTFLL
902      CVVNEADKLIF  TRAV12-1*01  TRAJ34*01             2  YLQPRTFLL
903      CVVNEENDMRF  TRAV12-1*01  TRAJ43*01             2  YLQPRTFLL
904      CVVNEGDKIIF  TRAV12-1*01  TRAJ30*01             2  YLQPRTFLL
905      CVVNEGDKLIF  TRAV12-1*01  TRAJ34*01             3  YLQPRTFLL
906      CVVNENNDMRF  TRAV12-1*01  TRAJ43*01             2  YLQPRTFLL
907      CVVNGADKLIF  TRAV12-1*01  TRAJ34*01             2  YLQPRTFLL
908      CVVNGGDKIIF  TRAV12-1*01  TRAJ30*01             2  YLQPRTFLL

=== IVTDFSVIK | public+specific: 0 / total: 529 ===

=== LLAGIGTVPI | public+specific: 0 / total: 412 ===

=== RLRAEAQVK | public+specific: 0 / total: 401 ===

=== GLCTLVAML | public+specific: 19 / total: 380 ===

       cdr3_alpha   v_alpha    j_alpha  reference_id    epitope
939   CADDNNARLMF  TRAV5*01  TRAJ31*01             3  GLCTLVAML
940   CAEDANARLMF  TRAV5*01  TRAJ31*01             2  GLCTLVAML
941   CAEDDNARLMF  TRAV5*01  TRAJ31*01             2  GLCTLVAML
942   CAEDFNARLMF  TRAV5*01  TRAJ31*01             2  GLCTLVAML
943   CAEDNNARLMF  TRAV4*01  TRAJ31*01             2  GLCTLVAML
944   CAEDQNARLMF  TRAV5*01  TRAJ31*01             2  GLCTLVAML
945   CAEDSNARLMF  TRAV5*01  TRAJ31*01             4  GLCTLVAML
946   CAEKGGTALIF  TRAV5*01  TRAJ15*01             2  GLCTLVAML
947    CAESIGKLIF  TRAV5*01  TRAJ23*01             5  GLCTLVAML
948    CAESIGKLIF  TRAV5*01  TRAJ34*01             2  GLCTLVAML
949    CAESTGKLIF  TRAV5*01  TRAJ37*01             8  GLCTLVAML
950  CAESTSGGKLIF  TRAV5*01  TRAJ23*01             2  GLCTLVAML
951  CAESTSGGKLIF  TRAV5*01  TRAJ37*01             2  GLCTLVAML
952  CAESTSWGKLQF  TRAV5*01  TRAJ24*02             2  GLCTLVAML
953  CAEYSSASKIIF  TRAV5*01   TRAJ3*01             4  GLCTLVAML

=== TTDPSFLGRY | public+specific: 8 / total: 374 ===

        cdr3_alpha     v_alpha    j_alpha  reference_id     epitope
958   CALAGSQGNLIF  TRAV9-2*01  TRAJ42*01             2  TTDPSFLGRY
959   CALGGSQGNLIF  TRAV9-2*01  TRAJ42*01             3  TTDPSFLGRY
960    CALNTGNQFYF  TRAV9-2*01  TRAJ49*01             2  TTDPSFLGRY
961   CALSGTGNQFYF  TRAV9-2*01  TRAJ49*01             2  TTDPSFLGRY
962   CASGGSQGNLIF  TRAV9-2*01  TRAJ42*01             2  TTDPSFLGRY
963  CAVFSGNTGKLIF   TRAV21*01  TRAJ37*01             2  TTDPSFLGRY
964  CAVPGFGNEKLTF   TRAV20*01  TRAJ48*01             2  TTDPSFLGRY
965  CAVPHFGNEKLTF   TRAV20*01  TRAJ48*01             2  TTDPSFLGRY

=== SPRWYFYYL | public+specific: 4 / total: 374 ===

         cdr3_alpha     v_alpha    j_alpha  reference_id    epitope
966  CAVPLYSSASKIIF  TRAV8-4*01   TRAJ3*01             2  SPRWYFYYL
967   CAVPNFGNEKLTF  TRAV8-2*01  TRAJ48*01             3  SPRWYFYYL
968  CAVPSYSSASKIIF  TRAV8-2*01   TRAJ3*01             2  SPRWYFYYL
969    CLVGDQGGKLIF    TRAV4*01  TRAJ23*01             2  SPRWYFYYL

=== LLLGIGILV | public+specific: 0 / total: 360 ===

=== ELAGIGILTV | public+specific: 1 / total: 355 ===

       cdr3_alpha      v_alpha    j_alpha  reference_id     epitope
970  CAGGGGADGLTF  TRAV12-2*01  TRAJ45*01             2  ELAGIGILTV

=== SSLENFRAYV | public+specific: 0 / total: 286 ===

=== LLWNGPMAV | public+specific: 9 / total: 267 ===

       cdr3_alpha      v_alpha    j_alpha  reference_id    epitope
971    CAGSASKIIF  TRAV12-2*01   TRAJ3*01             2  LLWNGPMAV
972    CATGDDKIIF  TRAV12-2*01  TRAJ30*01             2  LLWNGPMAV
973    CAVIAGKSTF  TRAV12-2*01  TRAJ27*01             3  LLWNGPMAV
974    CAVIGDKIIF  TRAV12-2*01  TRAJ30*01             2  LLWNGPMAV
975  CAVNSDGQKLLF  TRAV12-2*01     TRAJ16             2  LLWNGPMAV
976    CAVSDDKIIF  TRAV12-2*01  TRAJ30*01             2  LLWNGPMAV
977    CAVSNARLMF  TRAV12-2*01  TRAJ31*01             2  LLWNGPMAV
978   CAVSSTDKLIF  TRAV12-2*01  TRAJ34*01             2  LLWNGPMAV
979    CAVTDDKIIF  TRAV12-2*01  TRAJ30*01             2  LLWNGPMAV

=== VMATRRNVL | public+specific: 0 / total: 253 ===

=== SSYRRPVGI | public+specific: 0 / total: 253 ===

=== ASNENMETM | public+specific: 0 / total: 243 ===

=== CINGVCWTV | public+specific: 0 / total: 238 ===

In [112]:
clono_df.groupby('epitope').count()

            cdr3_alpha  v_alpha  j_alpha  reference_id
epitope
ELAGIGILTV           1        1        1             1
GILGFVFTL          870      870      870           870
GLCTLVAML           19       19       19            19
LLWNGPMAV            9        9        9             9
NLVPMVATV           12       12       12            12
RAKFKQLL            12       12       12            12
SPRWYFYYL            4        4        4             4
TTDPSFLGRY           8        8        8             8
YLQPRTFLL           45       45       45            45