In [2]:
import pandas as pd
from tqdm import tqdm

In [3]:
vdjdb = pd.read_csv('/projects/immunestatus/vdjdb/vdjdb-2025-07-30/cluster_members.txt', sep='\t')
vdjdb

,species,antigen.epitope,antigen.gene,antigen.species,mhc.a,mhc.b,mhc.class,gene,cdr3aa,x,y,cid,csz,v.segm,j.segm,v.end,j.start,v.segm.repr,j.segm.repr
0,HomoSapiens,ALSKGVHFV,ORF3,SARS-CoV-2,HLA-A*02:01,B2M,MHCI,TRB,CASSLSGDDYNEQFF,102.447143,32.107434,H.B.ALSKGVHFV.1,5,TRBV27*01,TRBJ2-1*01,5,9,TRBV27*01,TRBJ2-1*01
1,HomoSapiens,ALSKGVHFV,ORF3,SARS-CoV-2,HLA-A*02:01,B2M,MHCI,TRB,CASSLAGDDYNEQFF,36.799698,2.795705,H.B.ALSKGVHFV.1,5,TRBV27*01,TRBJ2-1*01,5,9,TRBV27*01,TRBJ2-1*01
2,HomoSapiens,ALSKGVHFV,ORF3,SARS-CoV-2,HLA-A*02:01,B2M,MHCI,TRB,CASSLAGDNYNEQFF,3.568838,-52.141266,H.B.ALSKGVHFV.1,5,TRBV27*01,TRBJ2-1*01,5,9,TRBV27*01,TRBJ2-1*01
3,HomoSapiens,ALSKGVHFV,ORF3,SARS-CoV-2,HLA-A*02:01,B2M,MHCI,TRB,CASSLAGDSYNEQFF,-36.541775,-2.006452,H.B.ALSKGVHFV.1,5,TRBV27*01,TRBJ2-1*01,5,8,TRBV27*01,TRBJ2-1*01
4,HomoSapiens,ALSKGVHFV,ORF3,SARS-CoV-2,HLA-A*02:01,B2M,MHCI,TRB,CASSLVGDSYNEQFF,-105.450820,18.494963,H.B.ALSKGVHFV.1,5,TRBV27*01,TRBJ2-1*01,5,8,TRBV27*01,TRBJ2-1*01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35563,MusMusculus,TVYGFCLL,m139,MCMV,H-2Kb,B2M,MHCI,TRA,CAASENYNQGKLIF,308.410316,128.603566,M.A.TVYGFCLL.2,12,"TRAV7-4*01,TRAV7D-4*01",TRAJ23*01,5,5,TRAV12D-1*01,TRAJ23*01
35564,MusMusculus,TVYGFCLL,m139,MCMV,H-2Kb,B2M,MHCI,TRA,CALIMNYNQGKLIF,187.064152,-192.603423,M.A.TVYGFCLL.2,12,TRAV12D-1*01,TRAJ23*01,3,5,TRAV12D-1*01,TRAJ23*01
35565,MusMusculus,TVYGFCLL,m139,MCMV,H-2Kb,B2M,MHCI,TRA,CALIPNYNQGKLIF,267.595691,-180.697136,M.A.TVYGFCLL.2,12,TRAV12D-1*01,TRAJ23*01,3,5,TRAV12D-1*01,TRAJ23*01
35566,MusMusculus,TVYGFCLL,m139,MCMV,H-2Kb,B2M,MHCI,TRA,CALRENYNQGKLIF,242.143769,-43.271264,M.A.TVYGFCLL.2,12,TRAV12-3*01,TRAJ23*01,3,5,TRAV12D-1*01,TRAJ23*01
35567,MusMusculus,TVYGFCLL,m139,MCMV,H-2Kb,B2M,MHCI,TRA,CALRMNYNQGKLIF,181.778883,-119.780217,M.A.TVYGFCLL.2,12,TRAV12D-1*01,TRAJ23*01,3,5,TRAV12D-1*01,TRAJ23*01

In [14]:
ebv = vdjdb[(vdjdb.species == 'HomoSapiens') & (vdjdb['antigen.species'] == 'EBV') & (vdjdb['gene'] == 'TRB')]

In [15]:
ebv['mhc.a'].value_counts()

mhc.a
HLA-A*02:01    272
HLA-B*08:01    113
HLA-A*11:01     18
HLA-B*35:01     15
HLA-B*07:02      7
Name: count, dtype: int64

In [16]:
ebv

,species,antigen.epitope,antigen.gene,antigen.species,mhc.a,mhc.b,mhc.class,gene,cdr3aa,x,y,cid,csz,v.segm,j.segm,v.end,j.start,v.segm.repr,j.segm.repr
50,HomoSapiens,AVFDRKSDAK,EBNA3B,EBV,HLA-A*11:01,B2M,MHCI,TRB,CASSVTSATGELFF,631.359443,97.958253,H.B.AVFDRKSDAK.11,8,TRBV28*01,TRBJ2-2*01,4,8,TRBV28*01,TRBJ2-2*01
51,HomoSapiens,AVFDRKSDAK,EBNA3B,EBV,HLA-A*11:01,B2M,MHCI,TRB,CASSWSYEQYF,138.273388,-163.643866,H.B.AVFDRKSDAK.5,5,TRBV6-3*01,TRBJ2-7*01,4,5,TRBV6-3*01,TRBJ2-7*01
52,HomoSapiens,AVFDRKSDAK,EBNA3B,EBV,HLA-A*11:01,B2M,MHCI,TRB,CASSYGYEQYF,146.193149,-23.973978,H.B.AVFDRKSDAK.5,5,TRBV19*01,TRBJ2-7*01,4,6,TRBV6-3*01,TRBJ2-7*01
53,HomoSapiens,AVFDRKSDAK,EBNA3B,EBV,HLA-A*11:01,B2M,MHCI,TRB,CASSYSYEQYF,157.471857,-99.857884,H.B.AVFDRKSDAK.5,5,TRBV6-5*01,TRBJ2-7*01,5,5,TRBV6-3*01,TRBJ2-7*01
81,HomoSapiens,AVFDRKSDAK,EBNA3B,EBV,HLA-A*11:01,B2M,MHCI,TRB,CASSFSYEQYF,196.089794,-153.848467,H.B.AVFDRKSDAK.5,5,TRBV6-3*01,TRBJ2-7*01,4,5,TRBV6-3*01,TRBJ2-7*01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34345,HomoSapiens,YVLDHLIVV,BRLF1,EBV,HLA-A*02:01,B2M,MHCI,TRB,CASSPHLGAAAEQYF,90.498679,-692.335002,H.B.YVLDHLIVV.6,5,TRBV19*01,TRBJ2-7*01,4,11,TRBV19*01,TRBJ2-7*01
34346,HomoSapiens,YVLDHLIVV,BRLF1,EBV,HLA-A*02:01,B2M,MHCI,TRB,CASSPHLGVAAEQYF,161.660302,-668.975452,H.B.YVLDHLIVV.6,5,TRBV19*01,TRBJ2-7*01,4,11,TRBV19*01,TRBJ2-7*01
34347,HomoSapiens,YVLDHLIVV,BRLF1,EBV,HLA-A*02:01,B2M,MHCI,TRB,CASSPHSGAAAEQYF,113.194982,-763.151739,H.B.YVLDHLIVV.6,5,TRBV19*01,TRBJ2-7*01,4,11,TRBV19*01,TRBJ2-7*01
34348,HomoSapiens,YVLDHLIVV,BRLF1,EBV,HLA-A*02:01,B2M,MHCI,TRB,CASSPLLGSNQPQHF,-671.692599,-294.340903,H.B.YVLDHLIVV.3,6,TRBV19*01,TRBJ1-5*01,4,8,TRBV19*01,TRBJ1-5*01
34349,HomoSapiens,YVLDHLIVV,BRLF1,EBV,HLA-A*02:01,B2M,MHCI,TRB,CASSQLLGSNQPQHF,-718.354122,-329.911657,H.B.YVLDHLIVV.3,6,TRBV6-5*01,TRBJ1-5*01,4,8,TRBV19*01,TRBJ1-5*01

In [2]:
meta = pd.read_csv('/projects/fmba_covid/hip_full/metadata.txt', sep='\t').drop(columns=['file_name', '..filter..'])

In [3]:
meta = meta[~meta.hla.isna()]

In [4]:
meta

,sample_id,age,race,sex,cmv,hla
0,HIP00110,55.0,NaN,male,-,"HLA-A*03,HLA-A*24,HLA-B*07"
1,HIP00169,41.0,NaN,male,-,"HLA-A*01,HLA-A*02,HLA-B*27,HLA-B*37"
2,HIP00594,21.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*32,HLA-B*07,HLA-B*61"
3,HIP00602,45.0,NaN,female,-,"HLA-A*02,HLA-A*11,HLA-B*35,HLA-B*51"
4,HIP00614,27.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*03,HLA-A*29,HLA-B*07"
...,...,...,...,...,...,...
661,HIP17887,NaN,NaN,NaN,NaN,"HLA-A*02,HLA-A*29,HLA-B*07,HLA-B*44"
662,HIP19048,57.0,NaN,female,-,"HLA-A*01,HLA-A*02,HLA-B*51,HLA-B*57"
663,HIP19089,NaN,NaN,NaN,NaN,"HLA-A*01,HLA-A*80,HLA-B*13,HLA-B*44"
664,HIP19716,NaN,NaN,NaN,NaN,"HLA-A*01,HLA-B*08"
665,HIP19717,48.0,hispanic or latino,male,+,"HLA-A*01,HLA-B*18,HLA-B*35"

In [5]:
cmv_positive = meta[(meta.cmv == '+') & (meta.hla.str.contains('A*02')) & (meta.hla.str.contains('B*07'))].reset_index(
    drop=True)

In [6]:
cmv_positive

,sample_id,age,race,sex,cmv,hla
0,HIP00594,21.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*32,HLA-B*07,HLA-B*61"
1,HIP00777,22.0,NaN,male,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*27"
2,HIP03370,41.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*02,HLA-B*07,HLA-B*52"
3,HIP03511,48.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*23,HLA-B*07,HLA-B*27"
4,HIP03720,38.0,NaN,male,+,"HLA-A*02,HLA-A*26,HLA-B*07,HLA-B*60"
5,HIP04509,26.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*14"
6,HIP05559,21.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*03,HLA-B*05,HLA-B*07"
7,HIP05590,49.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*23,HLA-B*07,HLA-B*44"
8,HIP05815,NaN,NaN,male,+,"HLA-A*01,HLA-A*02,HLA-B*07,HLA-B*61"
9,HIP05960,NaN,NaN,male,+,"HLA-A*02,HLA-A*11,HLA-B*07"
10,HIP08653,52.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*01,HLA-A*02,HLA-B*07,HLA-B*08"
11,HIP08986,34.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*62"
12,HIP09020,58.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*27"
13,HIP10424,37.0,NaN,female,+,"HLA-A*02,HLA-A*24,HLA-B*07,HLA-B*62"
14,HIP10716,61.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*15"
15,HIP11937,55.0,"black or african american,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*68,HLA-B*07,HLA-B*08"
16,HIP12900,28.0,"black or african american,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*33,HLA-B*07,HLA-B*15"
17,HIP13513,56.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*24,HLA-B*07,HLA-B*35"
18,HIP13903,43.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*29,HLA-B*07,HLA-B*08"
19,HIP13967,47.0,"asian or pacific islander,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*40"
20,HIP13986,53.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*51"
21,HIP13994,64.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-B*07,HLA-B*44"
22,HIP14041,52.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*24,HLA-B*07,HLA-B*55"
23,HIP14051,48.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*11,HLA-B*07,HLA-B*44"
24,HIP14157,23.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-B*07,HLA-B*14"
25,HIP14194,46.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*03,HLA-B*07,HLA-B*27"
26,HIP14227,45.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*23,HLA-B*07,HLA-B*44"
27,HIP15854,30.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*23,HLA-B*07,HLA-B*58"

In [6]:
for sample_name in tqdm(cmv_positive.sample_id):
    df = pd.read_csv(f'/projects/fmba_covid/hip_full/corr/{sample_name}.txt', sep='\t').rename(columns={
        'cdr3aa': 'junction_aa',
        'v': 'v_call', 
        'j': 'j_call',
    })[['junction_aa', 'v_call', 'j_call', 'count']]
    
    df['v_call'] = df.v_call.apply(lambda x: x.split(',')[0])
    df['j_call'] = df.j_call.apply(lambda x: x.split(',')[0])
    df['locus'] = 'beta'
    df = df[df.junction_aa.str.isalpha()]
    if len(df) > 100000:
        df = df[df['count'] > 1].drop(columns=['count'])
        df.to_csv(f'/projects/immunestatus/emerson/airr_format/{sample_name}.tsv', sep='\t', index=False)

100%|██████████| 28/28 [00:26<00:00,  1.04it/s]

In [46]:
meta

,sample_id,age,race,sex,cmv,hla
0,HIP00110,55.0,NaN,male,-,"HLA-A*03,HLA-A*24,HLA-B*07"
1,HIP00169,41.0,NaN,male,-,"HLA-A*01,HLA-A*02,HLA-B*27,HLA-B*37"
2,HIP00594,21.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*32,HLA-B*07,HLA-B*61"
3,HIP00602,45.0,NaN,female,-,"HLA-A*02,HLA-A*11,HLA-B*35,HLA-B*51"
4,HIP00614,27.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*03,HLA-A*29,HLA-B*07"
...,...,...,...,...,...,...
661,HIP17887,NaN,NaN,NaN,NaN,"HLA-A*02,HLA-A*29,HLA-B*07,HLA-B*44"
662,HIP19048,57.0,NaN,female,-,"HLA-A*01,HLA-A*02,HLA-B*51,HLA-B*57"
663,HIP19089,NaN,NaN,NaN,NaN,"HLA-A*01,HLA-A*80,HLA-B*13,HLA-B*44"
664,HIP19716,NaN,NaN,NaN,NaN,"HLA-A*01,HLA-B*08"
665,HIP19717,48.0,hispanic or latino,male,+,"HLA-A*01,HLA-B*18,HLA-B*35"

In [5]:
from collections import Counter
d = [*list(meta.hla.apply(lambda x: x.split(',')))]
counts = Counter(x for row in d for x in row)


alleles = []
# выводим результаты
for allele, cnt in counts.most_common()[:10]:
    if 'HLA-A' in allele:
        print(f"{allele}: {cnt}")
        alleles.append(allele)

HLA-A*02: 294
HLA-A*01: 186
HLA-A*03: 153
HLA-A*24: 129
HLA-A*11: 61

In [6]:
alleles

['HLA-A*02', 'HLA-A*01', 'HLA-A*03', 'HLA-A*24', 'HLA-A*11']

In [7]:
from collections import Counter
d = [*list(meta.hla.apply(lambda x: x.split(',')))]
counts = Counter(x for row in d for x in row)


# alleles = []
# выводим результаты
for allele, cnt in counts.most_common()[:10]:
    if 'HLA-A' in allele:
        print(f"{allele}: {cnt}")
        # alleles.append(allele)

HLA-A*02: 294
HLA-A*01: 186
HLA-A*03: 153
HLA-A*24: 129
HLA-A*11: 61

In [8]:
import pandas as pd

alleles_of_interest = ["HLA-A*01",
                       "HLA-A*24", "HLA-A*11","HLA-A*02", "HLA-A*03",]
interest_set = set(alleles_of_interest)

# превратим строку с аллелями в множество
def parse_hla(x: str) -> set:
    if pd.isna(x):
        return set()
    return set(a.strip() for a in str(x).split(",") if a.strip())

meta_now = meta[meta.cmv == '-'].copy()
meta_now["hla_set"] = meta_now["hla"].apply(parse_hla)

dfs = []
for allele in alleles_of_interest:
    # условие: образец содержит нужную аллель И больше НИКАКИХ других из интересующего списка
    def keep_row(s: set) -> bool:
        present_interest = s & interest_set
        return (allele in s) and (len(present_interest) == 1)

    subset = meta_now[meta_now["hla_set"].apply(keep_row)].copy()

    # берём до 5 (случайно; можно заменить на сортировку для детерминизма)
    k_samples = 7 if '24' in allele else (6 if '03' in allele else 5)
    print(k_samples)
    subset = subset.sample(n=min(k_samples, len(subset)), random_state=42)

    subset["allele"] = allele
    dfs.append(subset)

result = pd.concat(dfs, ignore_index=True).drop(columns=["hla_set"])
result

5
7
5
5
6

,sample_id,age,race,sex,cmv,hla,allele
0,HIP08345,NaN,NaN,male,-,"HLA-A*01,HLA-A*26,HLA-B*08,HLA-B*38",HLA-A*01
1,HIP13178,21.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*01,HLA-B*14,HLA-B*37",HLA-A*01
2,HIP13859,51.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*01,HLA-A*26,HLA-B*38,HLA-B*57",HLA-A*01
3,HIP13794,36.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*01,HLA-A*32,HLA-B*57,HLA-B*62",HLA-A*01
4,HIP03004,42.0,NaN,female,-,"HLA-A*01,HLA-A*25,HLA-B*08,HLA-B*44",HLA-A*01
5,HIP05934,33.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*24,HLA-A*32,HLA-B*08,HLA-B*39",HLA-A*24
6,HIP12538,24.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*24,HLA-A*26,HLA-B*35,HLA-B*38",HLA-A*24
7,HIP01055,29.0,NaN,female,-,"HLA-A*24,HLA-A*29,HLA-B*39,HLA-B*44",HLA-A*24
8,HIP14018,55.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*24,HLA-B*15,HLA-B*40",HLA-A*24
9,HIP09159,36.0,NaN,female,-,"HLA-A*24,HLA-A*32,HLA-B*44,HLA-B*62",HLA-A*24
10,HIP08230,35.0,NaN,female,-,"HLA-A*24,HLA-A*29,HLA-B*44,HLA-B*62",HLA-A*24
11,HIP10564,45.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*24,HLA-A*26,HLA-B*38,HLA-B*48",HLA-A*24
12,HIP14074,57.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*11,HLA-A*29,HLA-B*27,HLA-B*51",HLA-A*11
13,HIP14209,60.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*11,HLA-A*26,HLA-B*38,HLA-B*40",HLA-A*11
14,HIP00825,10.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*11,HLA-A*25,HLA-B*27,HLA-B*58",HLA-A*11
15,HIP14911,42.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*11,HLA-A*32,HLA-B*07,HLA-B*15",HLA-A*11
16,HIP12143,42.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*11,HLA-A*25,HLA-B*18,HLA-B*44",HLA-A*11
17,HIP04576,15.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*02,HLA-A*30,HLA-B*07,HLA-B*18",HLA-A*02
18,HIP00640,37.0,NaN,female,-,"HLA-A*02,HLA-A*68,HLA-B*27,HLA-B*44",HLA-A*02
19,HIP13722,31.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*02,HLA-A*30,HLA-B*07,HLA-B*41",HLA-A*02
20,HIP00826,38.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*02,HLA-A*23,HLA-B*49,HLA-B*62",HLA-A*02
21,HIP13871,41.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*02,HLA-A*32,HLA-B*37,HLA-B*62",HLA-A*02
22,HIP14230,62.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*03,HLA-A*33,HLA-B*15,HLA-B*35",HLA-A*03
23,HIP13402,NaN,NaN,female,-,"HLA-A*03,HLA-A*30,HLA-B*07,HLA-B*13",HLA-A*03
24,HIP10376,35.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*03,HLA-A*23,HLA-B*35,HLA-B*44",HLA-A*03
25,HIP14077,25.0,NaN,male,-,"HLA-A*03,HLA-A*33,HLA-B*07,HLA-B*50",HLA-A*03
26,HIP05409,16.0,"caucasian,non-hispanic or latino",male,-,"HLA-A*03,HLA-B*35",HLA-A*03
27,HIP05578,29.0,"caucasian,non-hispanic or latino",female,-,"HLA-A*03,HLA-A*30,HLA-B*14,HLA-B*51",HLA-A*03

In [ ]:
a02_negative = meta[(meta.cmv == '+') & (meta.hla.apply(lambda x: 'A*02' not in x)) & (meta.hla.str.contains('B*07'))].reset_index(
    drop=True).dropna().reset_index(drop=True)

In [ ]:
a02_negative

,sample_id,age,race,sex,cmv,hla
0,HIP00851,34.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*24,HLA-A*26,HLA-B*07,HLA-B*44"
1,HIP03275,54.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*11,HLA-B*07,HLA-B*55"
2,HIP04578,42.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-A*24,HLA-B*07"
3,HIP05832,54.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-B*07,HLA-B*51"
4,HIP08521,39.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*01,HLA-A*24,HLA-B*07,HLA-B*37"
5,HIP08792,51.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*29,HLA-A*31,HLA-B*07,HLA-B*44"
6,HIP13214,43.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*29,HLA-B*07,HLA-B*27"
7,HIP13324,55.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*11,HLA-B*07,HLA-B*35"
8,HIP13703,49.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*11,HLA-A*29,HLA-B*07,HLA-B*44"
9,HIP13800,66.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-A*68,HLA-B*07,HLA-B*08"
10,HIP13814,41.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*01,HLA-A*03,HLA-B*07,HLA-B*57"
11,HIP13856,23.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-A*32,HLA-B*07,HLA-B*35"
12,HIP13951,5.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*68,HLA-B*07,HLA-B*35"
13,HIP13962,42.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-A*23,HLA-B*07,HLA-B*08"
14,HIP13976,36.0,hispanic or latino,male,+,"HLA-A*01,HLA-A*24,HLA-B*07,HLA-B*14"
15,HIP14071,45.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*68,HLA-B*07,HLA-B*13"
16,HIP14103,43.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*03,HLA-B*07,HLA-B*44"
17,HIP14124,37.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-B*07,HLA-B*50"
18,HIP14136,42.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*03,HLA-B*07,HLA-B*14"
19,HIP14183,57.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*03,HLA-B*07,HLA-B*08"
20,HIP14236,56.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-A*24,HLA-B*07,HLA-B*15"
21,HIP17462,47.0,"asian or pacific islander,non-hispanic or latino",male,+,"HLA-A*11,HLA-A*24,HLA-B*07,HLA-B*08"

In [ ]:
a02_negative = a02_negative.sort_values(by='hla', ascending=False).head(4)

In [36]:
a02_negative

,sample_id,age,race,sex,cmv,hla
5,HIP08792,51.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*29,HLA-A*31,HLA-B*07,HLA-B*44"
0,HIP00851,34.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*24,HLA-A*26,HLA-B*07,HLA-B*44"
8,HIP13703,49.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*11,HLA-A*29,HLA-B*07,HLA-B*44"
21,HIP17462,47.0,"asian or pacific islander,non-hispanic or latino",male,+,"HLA-A*11,HLA-A*24,HLA-B*07,HLA-B*08"

In [37]:
control_samples = []
for sample_name in tqdm(a02_negative.sample_id):
    df = pd.read_csv(f'/projects/fmba_covid/hip_full/corr/{sample_name}.txt', sep='\t').rename(columns={
        'cdr3aa': 'junction_aa',
        'v': 'v_call', 
        'j': 'j_call',
    })[['junction_aa', 'v_call', 'j_call']]
    
    df['v_call'] = df.v_call.apply(lambda x: x.split(',')[0])
    df['j_call'] = df.j_call.apply(lambda x: x.split(',')[0])
    df['locus'] = 'beta'
    df = df[df.junction_aa.str.isalpha()]
    if len(df) > 100000:
        control_samples.append(df)

100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

In [38]:
[len(x) for x in control_samples]

[249434, 293854, 216435]

In [39]:
control_sample = pd.concat(control_samples)

In [40]:
control_sample

              junction_aa    v_call   j_call locus
0           CASSLVGFNEQFF   TRBV4-2  TRBJ2-1  beta
3          CASTRRQGGKGYTF  TRBV10-1  TRBJ1-2  beta
4       CASSSHETTGGSSPLHF   TRBV7-9  TRBJ1-6  beta
5           CATSTVAGEEQFF    TRBV15  TRBJ2-1  beta
6         CASSPGTVYNSPLHF   TRBV6-5  TRBJ1-6  beta
...                   ...       ...      ...   ...
255105  CASSFLTGGSGANVLTF   TRBV5-6  TRBJ2-6  beta
255106  CASSFLGAQADNSPLHF   TRBV5-6  TRBJ1-6  beta
255110         CASSEKTQYF  TRBV25-1  TRBJ2-5  beta
255112        CATSREESAFF    TRBV15  TRBJ1-1  beta
255114        CATSVEGIWFF    TRBV15  TRBJ1-4  beta

[759723 rows x 4 columns]

In [41]:
control_sample.to_csv('/projects/immunestatus/emerson/airr_format/control_ebv.tsv', sep='\t', index=False)

In [18]:
for x in result.allele.unique():
    print(x, ' '.join(result[result.allele == x].sample_id))

HLA-A*01 HIP08345 HIP13178 HIP13859 HIP13794 HIP03004
HLA-A*24 HIP05934 HIP12538 HIP01055 HIP14018 HIP09159 HIP08230 HIP10564
HLA-A*11 HIP14074 HIP14209 HIP00825 HIP14911 HIP12143
HLA-A*02 HIP04576 HIP00640 HIP13722 HIP00826 HIP13871
HLA-A*03 HIP14230 HIP13402 HIP10376 HIP14077 HIP05409 HIP05578

In [65]:
for sample_name in result.sample_id:
    print(f'processing {sample_name}')
    df = pd.read_csv(f'/projects/fmba_covid/hip_full/corr/{sample_name}.txt', sep='\t').rename(columns={
        'cdr3aa': 'junction_aa',
        'v': 'v_call', 
        'j': 'j_call',
    })[['junction_aa', 'v_call', 'j_call', 'count']]
    
    df['v_call'] = df.v_call.apply(lambda x: x.split(',')[0])
    df['j_call'] = df.j_call.apply(lambda x: x.split(',')[0])
    df['locus'] = 'beta'
    df = df[df.junction_aa.str.isalpha()]
    if len(df) > 100000:
        df = df[df['count'] > 1].drop(columns=['count'])
        df.to_csv(f'/projects/immunestatus/emerson_hla/airr_format/{sample_name}.tsv', sep='\t', index=False)
    else:
        print(f'error processing {sample_name}')

processing HIP08345
processing HIP13178
processing HIP13859
processing HIP13794
processing HIP03004
processing HIP05934
error processing HIP05934
processing HIP12538
processing HIP01055
error processing HIP01055
processing HIP14018
processing HIP09159
processing HIP08230
processing HIP10564
processing HIP14074
processing HIP14209
processing HIP00825
processing HIP14911
processing HIP12143
processing HIP04576
processing HIP00640
processing HIP13722
processing HIP00826
processing HIP13871
processing HIP14230
processing HIP13402
error processing HIP13402
processing HIP10376
processing HIP14077
processing HIP05409
processing HIP05578

In [12]:
result[~result.sample_id.isin(['HIP13402', 'HIP01055', 'HIP05934'])].reset_index(
    drop=True).to_csv('/projects/immunestatus/emerson_hla/airr_format/metadata.tsv', sep='\t', index=False)

In [7]:
import pandas as pd

alleles_of_interest = ["HLA-A*01",
                       "HLA-A*24", "HLA-A*11","HLA-A*02", "HLA-A*03",]
interest_set = set(alleles_of_interest)

# превратим строку с аллелями в множество
def parse_hla(x: str) -> set:
    if pd.isna(x):
        return set()
    return set(a.strip() for a in str(x).split(",") if a.strip())

meta_now = meta[meta.cmv == '+'].copy()
meta_now["hla_set"] = meta_now["hla"].apply(parse_hla)

dfs = []
for allele in alleles_of_interest:
    # условие: образец содержит нужную аллель И больше НИКАКИХ других из интересующего списка
    def keep_row(s: set) -> bool:
        present_interest = s & interest_set
        return (allele in s) and (len(present_interest) == 1)

    subset = meta_now[meta_now["hla_set"].apply(keep_row)].copy()

    # берём до 5 (случайно; можно заменить на сортировку для детерминизма)
    k_samples = 7 if '24' in allele else (6 if '03' in allele else 5)
    print(k_samples)
    subset = subset.sample(n=min(k_samples, len(subset)), random_state=42)

    subset["allele"] = allele
    dfs.append(subset)

result = pd.concat(dfs, ignore_index=True).drop(columns=["hla_set"])
result

5
7
5
5
6

,sample_id,age,race,sex,cmv,hla,allele
0,HIP04605,56.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*26,HLA-B*08,HLA-B*22",HLA-A*01
1,HIP13822,48.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*01,HLA-A*66,HLA-B*08,HLA-B*58",HLA-A*01
2,HIP00775,39.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*66,HLA-B*41,HLA-B*57",HLA-A*01
3,HIP14175,59.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*68,HLA-B*18,HLA-B*56",HLA-A*01
4,HIP10669,32.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*01,HLA-A*30,HLA-B*08,HLA-B*13",HLA-A*01
5,HIP00851,34.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*24,HLA-A*26,HLA-B*07,HLA-B*44",HLA-A*24
6,HIP13489,44.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*24,HLA-A*25,HLA-B*18,HLA-B*51",HLA-A*24
7,HIP11513,9.0,"asian or pacific islander,non-hispanic or latino",female,+,"HLA-A*24,HLA-A*34,HLA-B*15,HLA-B*40",HLA-A*24
8,HIP02024,51.0,NaN,male,+,"HLA-A*24,HLA-A*68,HLA-B*51,HLA-B*55",HLA-A*24
9,HIP13667,54.0,NaN,male,+,"HLA-A*24,HLA-A*31,HLA-B*27",HLA-A*24
10,HIP05405,40.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*24,HLA-A*30,HLA-B*18",HLA-A*24
11,HIP17370,44.0,NaN,female,+,"HLA-A*24,HLA-A*26,HLA-B*07,HLA-B*61",HLA-A*24
12,HIP13919,46.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*11,HLA-A*29,HLA-B*15,HLA-B*18",HLA-A*11
13,HIP05437,28.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*11,HLA-A*26,HLA-B*35,HLA-B*62",HLA-A*11
14,HIP13703,49.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*11,HLA-A*29,HLA-B*07,HLA-B*44",HLA-A*11
15,HIP02078,27.0,NaN,male,+,"HLA-A*11,HLA-A*30,HLA-B*35,HLA-B*39",HLA-A*11
16,HIP13992,20.0,hispanic or latino,male,+,"HLA-A*11,HLA-A*36,HLA-B*35,HLA-B*37",HLA-A*11
17,HIP00985,53.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*26,HLA-B*14,HLA-B*27",HLA-A*02
18,HIP14152,48.0,hispanic or latino,male,+,"HLA-A*02,HLA-A*68,HLA-B*39,HLA-B*52",HLA-A*02
19,HIP05311,48.0,"black or african american,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*74,HLA-B*53,HLA-B*70",HLA-A*02
20,HIP00594,21.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*02,HLA-A*32,HLA-B*07,HLA-B*61",HLA-A*02
21,HIP09430,23.0,"asian or pacific islander,non-hispanic or latino",female,+,"HLA-A*02,HLA-A*26,HLA-B*08,HLA-B*40",HLA-A*02
22,HIP10814,NaN,NaN,male,+,"HLA-A*03,HLA-A*32,HLA-B*07,HLA-B*35",HLA-A*03
23,HIP13856,23.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-A*32,HLA-B*07,HLA-B*35",HLA-A*03
24,HIP05434,36.0,"caucasian,non-hispanic or latino",male,+,"HLA-A*03,HLA-B*35",HLA-A*03
25,HIP13880,49.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*30,HLA-B*18,HLA-B*35",HLA-A*03
26,HIP13318,NaN,NaN,female,+,"HLA-A*03,HLA-B*14",HLA-A*03
27,HIP13214,43.0,"caucasian,non-hispanic or latino",female,+,"HLA-A*03,HLA-A*29,HLA-B*07,HLA-B*27",HLA-A*03